Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('DCM_IN_FTP_ID', '108');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('DCM_OUT_FTP_ID', '102');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_KAU', 'KAUDCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_LHE', 'LHEDCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_LUR', 'LURDCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_MAT', 'MATDCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_MAU', 'MAUDCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_MHI', 'MHIDCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_MKA', 'MKADCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_MKI', 'MKIDCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_MLE', 'MLEDCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_MLI', 'MLIDCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_MNA', 'MNADCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_MWI', 'MWIDCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_RJP', 'RJPDCMGRP@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_KAH', 'bargeplankah@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_NAW', '1MHROPS@matson.com;SIMAMURA@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_GM', 'sysreports@matson.com;1Grp_SLC@matson.com;1dihon@matson.com;BRogers@matson.com;Jchagami@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_LHMA', 'MatsonSLC@ssofa.com;srpt@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_BMA', 'dkirker@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_NCB', 'MCSHAWAII@HAWAII.RR.COM;dkirker@matson.com;jsakamoto@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_SHIPP_HON', '1SHIPP_HON@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_HIL', '1MatNavatHilo@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_DCM_KHI', '1MatNavatHilo@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( ‘EMAIL_GATE_TEMP’,'SN4Test@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( ‘EMAIL_USCG_GRP’,'SN4Test@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ( 'EMAIL_LATE_DCM','honsystems@matson.com, datasupport@matson.com, ldohanyos@matson.com, sysreports@matson.com');
insert into TOSCSTMMGR.TOS_APP_PARAMETER ( KEY, VALUE) values ('EMAIL_NEW_VES', '1sn4supt@matson.com');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('FSS_FILES_FTP_ID', '106');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('FTP_DCM_REP', '102');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('FTP_ID_CMIS', '103');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('FTP_ID_N4', '109');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('MAIL_HOST', 'mailhost-core.vsvcs.cscehub.com');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('MAX_MESSAGE_TO_SEND', '10');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('MQ_CHANNEL', 'CUSTOMS.SVRCON');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('MQ_HOSTNAME', '10.8.7.145');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('MQ_QUEUE_MGR_NAME', 'UNXDEV1');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('MQ_QUEUE_NAME', 'ACETS.TOS.N4.FORMATTED');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('NOW_DYNAMIC', 'TRUE');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('NOW_URL', 'http://192.168.170.244 :10060/.wsdl');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('STIF_FILES_FTP_ID', '107');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('SUPPORT_EMAIL', '1SN4Supt@matson.com');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('SUP_FILES_FTP_ID', '105');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('TIMER_CANCEL_GATE', '120');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('TIMER_CMIS_FTP', '300');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('TIMER_DCM', '7');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('TIMER_MQ_PROC_INTERV', '1');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('TIMER_NEW_VES', '2');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('TIMER_STIF', '7');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('TIMER_VES_SCHEDULE', '10');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('VES_FILES_FTP_ID', '104');
Insert into TOS_APP_PARAMETER    (KEY, VALUE)  Values    ('log_level', 'debug');