package com.matson.tos.jatb;

// This is a class file generated by JATB. Please do not modify this file. 

public class DcmConvert {

	private java.lang.String vesvoy;
	private java.lang.String ctrNo;
	private java.lang.String cnSeq;
	private java.lang.String blankData1;
	private java.lang.String checkDigit;
	private java.lang.String hazClass;
	private java.lang.String hazClassDesc;
	private java.lang.String hazSubClass;
	private java.lang.String consignee;
	private java.lang.String pack;
	private java.lang.String blankData2;
	private java.lang.String hazDesc1;
	private java.lang.String emergencyContact;
	private java.lang.String grossWeightUnit;
	private java.lang.String cellLocation;
	private java.lang.String destPort;
	private java.lang.String yardLocation;
	private java.lang.String carsFlag;
	private java.lang.String shipment;
	private java.lang.String hazCode;
	private java.lang.String hazCodeType;
	private java.lang.String hazRegQualifier;
	private java.lang.String shippingName;
	private java.lang.String techName;
	private java.lang.String grossWeight;
	private java.lang.String grossUnit;
	private java.lang.String flashPoint;
	private java.lang.String packagingGrpMarks;
	private java.lang.String remarks;
	private java.lang.String emergencyResponse;
	private java.lang.String loadPort;
	private java.lang.String consigneeName;

	public java.lang.String getVesvoy() {
		return this.vesvoy;
	}
	public void setVesvoy( java.lang.String value) {
		this.vesvoy = value;
	}
	public java.lang.String getCtrNo() {
		return this.ctrNo;
	}
	public void setCtrNo( java.lang.String value) {
		this.ctrNo = value;
	}
	public java.lang.String getCnSeq() {
		return this.cnSeq;
	}
	public void setCnSeq( java.lang.String value) {
		this.cnSeq = value;
	}
	public java.lang.String getBlankData1() {
		return this.blankData1;
	}
	public void setBlankData1( java.lang.String value) {
		this.blankData1 = value;
	}
	public java.lang.String getCheckDigit() {
		return this.checkDigit;
	}
	public void setCheckDigit( java.lang.String value) {
		this.checkDigit = value;
	}
	public java.lang.String getHazClass() {
		return this.hazClass;
	}
	public void setHazClass( java.lang.String value) {
		this.hazClass = value;
	}
	public java.lang.String getHazClassDesc() {
		return this.hazClassDesc;
	}
	public void setHazClassDesc( java.lang.String value) {
		this.hazClassDesc = value;
	}
	public java.lang.String getHazSubClass() {
		return this.hazSubClass;
	}
	public void setHazSubClass( java.lang.String value) {
		this.hazSubClass = value;
	}
	public java.lang.String getConsignee() {
		return this.consignee;
	}
	public void setConsignee( java.lang.String value) {
		this.consignee = value;
	}
	public java.lang.String getPack() {
		return this.pack;
	}
	public void setPack( java.lang.String value) {
		this.pack = value;
	}
	public java.lang.String getBlankData2() {
		return this.blankData2;
	}
	public void setBlankData2( java.lang.String value) {
		this.blankData2 = value;
	}
	public java.lang.String getHazDesc1() {
		return this.hazDesc1;
	}
	public void setHazDesc1( java.lang.String value) {
		this.hazDesc1 = value;
	}
	public java.lang.String getEmergencyContact() {
		return this.emergencyContact;
	}
	public void setEmergencyContact( java.lang.String value) {
		this.emergencyContact = value;
	}
	public java.lang.String getGrossWeightUnit() {
		return this.grossWeightUnit;
	}
	public void setGrossWeightUnit( java.lang.String value) {
		this.grossWeightUnit = value;
	}
	public java.lang.String getCellLocation() {
		return this.cellLocation;
	}
	public void setCellLocation( java.lang.String value) {
		this.cellLocation = value;
	}
	public java.lang.String getDestPort() {
		return this.destPort;
	}
	public void setDestPort( java.lang.String value) {
		this.destPort = value;
	}
	public java.lang.String getYardLocation() {
		return this.yardLocation;
	}
	public void setYardLocation( java.lang.String value) {
		this.yardLocation = value;
	}
	public java.lang.String getCarsFlag() {
		return this.carsFlag;
	}
	public void setCarsFlag( java.lang.String value) {
		this.carsFlag = value;
	}
	public java.lang.String getShipment() {
		return this.shipment;
	}
	public void setShipment( java.lang.String value) {
		this.shipment = value;
	}
	public java.lang.String getHazCode() {
		return this.hazCode;
	}
	public void setHazCode( java.lang.String value) {
		this.hazCode = value;
	}
	public java.lang.String getHazCodeType() {
		return this.hazCodeType;
	}
	public void setHazCodeType( java.lang.String value) {
		this.hazCodeType = value;
	}
	public java.lang.String getHazRegQualifier() {
		return this.hazRegQualifier;
	}
	public void setHazRegQualifier( java.lang.String value) {
		this.hazRegQualifier = value;
	}
	public java.lang.String getShippingName() {
		return this.shippingName;
	}
	public void setShippingName( java.lang.String value) {
		this.shippingName = value;
	}
	public java.lang.String getTechName() {
		return this.techName;
	}
	public void setTechName( java.lang.String value) {
		this.techName = value;
	}
	public java.lang.String getGrossWeight() {
		return this.grossWeight;
	}
	public void setGrossWeight( java.lang.String value) {
		this.grossWeight = value;
	}
	public java.lang.String getGrossUnit() {
		return this.grossUnit;
	}
	public void setGrossUnit( java.lang.String value) {
		this.grossUnit = value;
	}
	public java.lang.String getFlashPoint() {
		return this.flashPoint;
	}
	public void setFlashPoint( java.lang.String value) {
		this.flashPoint = value;
	}
	public java.lang.String getPackagingGrpMarks() {
		return this.packagingGrpMarks;
	}
	public void setPackagingGrpMarks( java.lang.String value) {
		this.packagingGrpMarks = value;
	}
	public java.lang.String getRemarks() {
		return this.remarks;
	}
	public void setRemarks( java.lang.String value) {
		this.remarks = value;
	}
	public java.lang.String getEmergencyResponse() {
		return this.emergencyResponse;
	}
	public void setEmergencyResponse( java.lang.String value) {
		this.emergencyResponse = value;
	}
	public java.lang.String getLoadPort() {
		return this.loadPort;
	}
	public void setLoadPort( java.lang.String value) {
		this.loadPort = value;
	}
	public java.lang.String getConsigneeName() {
		return this.consigneeName;
	}
	public void setConsigneeName( java.lang.String value) {
		this.consigneeName = value;
	}
}