//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tBaseReefer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tBaseReefer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="rfr-type" type="{http://www.navis.com/argo}tRfrType" />
 *       &lt;attribute name="is-super-freeze" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="is-controlled-atmosphere" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="is-temperature-controlled" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tBaseReefer")
@XmlSeeAlso({
    TReefer.class
})
public class TBaseReefer {

    @XmlAttribute(name = "rfr-type")
    protected TRfrType rfrType;
    @XmlAttribute(name = "is-super-freeze")
    protected String isSuperFreeze;
    @XmlAttribute(name = "is-controlled-atmosphere")
    protected String isControlledAtmosphere;
    @XmlAttribute(name = "is-temperature-controlled")
    protected String isTemperatureControlled;

    /**
     * Gets the value of the rfrType property.
     * 
     * @return
     *     possible object is
     *     {@link TRfrType }
     *     
     */
    public TRfrType getRfrType() {
        return rfrType;
    }

    /**
     * Sets the value of the rfrType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRfrType }
     *     
     */
    public void setRfrType(TRfrType value) {
        this.rfrType = value;
    }

    /**
     * Gets the value of the isSuperFreeze property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsSuperFreeze() {
        return isSuperFreeze;
    }

    /**
     * Sets the value of the isSuperFreeze property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSuperFreeze(String value) {
        this.isSuperFreeze = value;
    }

    /**
     * Gets the value of the isControlledAtmosphere property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsControlledAtmosphere() {
        return isControlledAtmosphere;
    }

    /**
     * Sets the value of the isControlledAtmosphere property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsControlledAtmosphere(String value) {
        this.isControlledAtmosphere = value;
    }

    /**
     * Gets the value of the isTemperatureControlled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTemperatureControlled() {
        return isTemperatureControlled;
    }

    /**
     * Sets the value of the isTemperatureControlled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTemperatureControlled(String value) {
        this.isTemperatureControlled = value;
    }

}
