//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A shipment from shipper to consignee being shipped together over the
 *                 same route.
 *             
 * 
 * <p>Java class for tBillOfLading complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tBillOfLading">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="items" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="reefer" type="{http://www.navis.com/argo}tReeferRequirements" minOccurs="0"/>
 *                             &lt;element name="cargo-lots" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="cargo-lot" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="unit-id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                                               &lt;attribute name="unit-key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="quantity" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                               &lt;attribute name="quantity-manifiested" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                               &lt;attribute name="quantity-discrepency" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                               &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                                               &lt;attribute name="brand" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                                               &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                                               &lt;attribute name="model" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="update-mode" type="{http://www.navis.com/argo}tUpdateMode" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="bulk-unit">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="GALLON"/>
 *                                 &lt;enumeration value="LITER"/>
 *                                 &lt;enumeration value="CUBICMETER"/>
 *                                 &lt;enumeration value="KG"/>
 *                                 &lt;enumeration value="MT"/>
 *                                 &lt;enumeration value="SHORTTON"/>
 *                                 &lt;enumeration value="LONGTON"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="commodity-id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                           &lt;attribute name="is-bulk" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="quantity" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="package-type" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                           &lt;attribute name="package-length-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="package-width-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="package-height-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="package-weight-kg" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="piece-quantity" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="piece-is-bulk" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="piece-bulk-unit">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="GALLON"/>
 *                                 &lt;enumeration value="LITER"/>
 *                                 &lt;enumeration value="CUBICMETER"/>
 *                                 &lt;enumeration value="KG"/>
 *                                 &lt;enumeration value="MT"/>
 *                                 &lt;enumeration value="SHORTTON"/>
 *                                 &lt;enumeration value="LONGTON"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="piece-package-type" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                           &lt;attribute name="piece-length-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="piece-width-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="piece-height-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="piece-weight-kg" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="product-type" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="update-mode" type="{http://www.navis.com/argo}tUpdateMode" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="goods-bl" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="unit-id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                 &lt;attribute name="unit-key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="nbr" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="line" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="carrier-visit" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="category" type="{http://www.navis.com/argo}tCategory" />
 *       &lt;attribute name="consignee-id" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="consignee-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="shipper-id" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="shipper-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="origin" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="destination" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="pol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pod-1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pod-2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bonded-destination" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="bond-trucking-company" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="notes" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="manifested-quantity" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="agent" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tBillOfLading", propOrder = {
    "items",
    "goodsBl"
})
public class TBillOfLading {

    protected TBillOfLading.Items items;
    @XmlElement(name = "goods-bl")
    protected List<TBillOfLading.GoodsBl> goodsBl;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nbr;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String line;
    @XmlAttribute(name = "carrier-visit", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String carrierVisit;
    @XmlAttribute
    protected TCategory category;
    @XmlAttribute(name = "consignee-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String consigneeId;
    @XmlAttribute(name = "consignee-name")
    protected String consigneeName;
    @XmlAttribute(name = "shipper-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String shipperId;
    @XmlAttribute(name = "shipper-name")
    protected String shipperName;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String origin;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String destination;
    @XmlAttribute
    protected String pol;
    @XmlAttribute(name = "pod-1")
    protected String pod1;
    @XmlAttribute(name = "pod-2")
    protected String pod2;
    @XmlAttribute(name = "bonded-destination")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String bondedDestination;
    @XmlAttribute(name = "bond-trucking-company")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String bondTruckingCompany;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String notes;
    @XmlAttribute(name = "manifested-quantity")
    protected Long manifestedQuantity;
    @XmlAttribute
    protected String agent;

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link TBillOfLading.Items }
     *     
     */
    public TBillOfLading.Items getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBillOfLading.Items }
     *     
     */
    public void setItems(TBillOfLading.Items value) {
        this.items = value;
    }

    /**
     * Gets the value of the goodsBl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the goodsBl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGoodsBl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TBillOfLading.GoodsBl }
     * 
     * 
     */
    public List<TBillOfLading.GoodsBl> getGoodsBl() {
        if (goodsBl == null) {
            goodsBl = new ArrayList<TBillOfLading.GoodsBl>();
        }
        return this.goodsBl;
    }

    /**
     * Gets the value of the nbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNbr() {
        return nbr;
    }

    /**
     * Sets the value of the nbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNbr(String value) {
        this.nbr = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine(String value) {
        this.line = value;
    }

    /**
     * Gets the value of the carrierVisit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierVisit() {
        return carrierVisit;
    }

    /**
     * Sets the value of the carrierVisit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierVisit(String value) {
        this.carrierVisit = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link TCategory }
     *     
     */
    public TCategory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCategory }
     *     
     */
    public void setCategory(TCategory value) {
        this.category = value;
    }

    /**
     * Gets the value of the consigneeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsigneeId() {
        return consigneeId;
    }

    /**
     * Sets the value of the consigneeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsigneeId(String value) {
        this.consigneeId = value;
    }

    /**
     * Gets the value of the consigneeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsigneeName() {
        return consigneeName;
    }

    /**
     * Sets the value of the consigneeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsigneeName(String value) {
        this.consigneeName = value;
    }

    /**
     * Gets the value of the shipperId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipperId() {
        return shipperId;
    }

    /**
     * Sets the value of the shipperId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipperId(String value) {
        this.shipperId = value;
    }

    /**
     * Gets the value of the shipperName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipperName() {
        return shipperName;
    }

    /**
     * Sets the value of the shipperName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipperName(String value) {
        this.shipperName = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the pol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPol() {
        return pol;
    }

    /**
     * Sets the value of the pol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPol(String value) {
        this.pol = value;
    }

    /**
     * Gets the value of the pod1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPod1() {
        return pod1;
    }

    /**
     * Sets the value of the pod1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPod1(String value) {
        this.pod1 = value;
    }

    /**
     * Gets the value of the pod2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPod2() {
        return pod2;
    }

    /**
     * Sets the value of the pod2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPod2(String value) {
        this.pod2 = value;
    }

    /**
     * Gets the value of the bondedDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBondedDestination() {
        return bondedDestination;
    }

    /**
     * Sets the value of the bondedDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBondedDestination(String value) {
        this.bondedDestination = value;
    }

    /**
     * Gets the value of the bondTruckingCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBondTruckingCompany() {
        return bondTruckingCompany;
    }

    /**
     * Sets the value of the bondTruckingCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBondTruckingCompany(String value) {
        this.bondTruckingCompany = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the manifestedQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getManifestedQuantity() {
        return manifestedQuantity;
    }

    /**
     * Sets the value of the manifestedQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setManifestedQuantity(Long value) {
        this.manifestedQuantity = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgent(String value) {
        this.agent = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="unit-id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *       &lt;attribute name="unit-key" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class GoodsBl {

        @XmlAttribute(name = "unit-id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String unitId;
        @XmlAttribute(name = "unit-key")
        protected String unitKey;

        /**
         * Gets the value of the unitId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitId() {
            return unitId;
        }

        /**
         * Sets the value of the unitId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitId(String value) {
            this.unitId = value;
        }

        /**
         * Gets the value of the unitKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitKey() {
            return unitKey;
        }

        /**
         * Sets the value of the unitKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitKey(String value) {
            this.unitKey = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="reefer" type="{http://www.navis.com/argo}tReeferRequirements" minOccurs="0"/>
     *                   &lt;element name="cargo-lots" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="cargo-lot" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="unit-id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *                                     &lt;attribute name="unit-key" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="quantity" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                                     &lt;attribute name="quantity-manifiested" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                                     &lt;attribute name="quantity-discrepency" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *                                     &lt;attribute name="brand" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *                                     &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *                                     &lt;attribute name="model" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="update-mode" type="{http://www.navis.com/argo}tUpdateMode" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="bulk-unit">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="GALLON"/>
     *                       &lt;enumeration value="LITER"/>
     *                       &lt;enumeration value="CUBICMETER"/>
     *                       &lt;enumeration value="KG"/>
     *                       &lt;enumeration value="MT"/>
     *                       &lt;enumeration value="SHORTTON"/>
     *                       &lt;enumeration value="LONGTON"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="commodity-id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *                 &lt;attribute name="is-bulk" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="quantity" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="package-type" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *                 &lt;attribute name="package-length-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="package-width-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="package-height-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="package-weight-kg" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                 &lt;attribute name="piece-quantity" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="piece-is-bulk" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="piece-bulk-unit">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="GALLON"/>
     *                       &lt;enumeration value="LITER"/>
     *                       &lt;enumeration value="CUBICMETER"/>
     *                       &lt;enumeration value="KG"/>
     *                       &lt;enumeration value="MT"/>
     *                       &lt;enumeration value="SHORTTON"/>
     *                       &lt;enumeration value="LONGTON"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="piece-package-type" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *                 &lt;attribute name="piece-length-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="piece-width-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="piece-height-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="piece-weight-kg" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                 &lt;attribute name="product-type" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="update-mode" type="{http://www.navis.com/argo}tUpdateMode" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class Items {

        protected List<TBillOfLading.Items.Item> item;
        @XmlAttribute(name = "update-mode")
        protected TUpdateMode updateMode;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TBillOfLading.Items.Item }
         * 
         * 
         */
        public List<TBillOfLading.Items.Item> getItem() {
            if (item == null) {
                item = new ArrayList<TBillOfLading.Items.Item>();
            }
            return this.item;
        }

        /**
         * Gets the value of the updateMode property.
         * 
         * @return
         *     possible object is
         *     {@link TUpdateMode }
         *     
         */
        public TUpdateMode getUpdateMode() {
            return updateMode;
        }

        /**
         * Sets the value of the updateMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUpdateMode }
         *     
         */
        public void setUpdateMode(TUpdateMode value) {
            this.updateMode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="reefer" type="{http://www.navis.com/argo}tReeferRequirements" minOccurs="0"/>
         *         &lt;element name="cargo-lots" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="cargo-lot" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="unit-id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
         *                           &lt;attribute name="unit-key" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="quantity" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *                           &lt;attribute name="quantity-manifiested" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *                           &lt;attribute name="quantity-discrepency" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}NCName" />
         *                           &lt;attribute name="brand" type="{http://www.w3.org/2001/XMLSchema}NCName" />
         *                           &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}NCName" />
         *                           &lt;attribute name="model" type="{http://www.w3.org/2001/XMLSchema}NCName" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="update-mode" type="{http://www.navis.com/argo}tUpdateMode" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="bulk-unit">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="GALLON"/>
         *             &lt;enumeration value="LITER"/>
         *             &lt;enumeration value="CUBICMETER"/>
         *             &lt;enumeration value="KG"/>
         *             &lt;enumeration value="MT"/>
         *             &lt;enumeration value="SHORTTON"/>
         *             &lt;enumeration value="LONGTON"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="commodity-id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
         *       &lt;attribute name="is-bulk" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="quantity" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="package-type" type="{http://www.w3.org/2001/XMLSchema}NCName" />
         *       &lt;attribute name="package-length-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="package-width-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="package-height-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="package-weight-kg" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *       &lt;attribute name="piece-quantity" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="piece-is-bulk" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="piece-bulk-unit">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="GALLON"/>
         *             &lt;enumeration value="LITER"/>
         *             &lt;enumeration value="CUBICMETER"/>
         *             &lt;enumeration value="KG"/>
         *             &lt;enumeration value="MT"/>
         *             &lt;enumeration value="SHORTTON"/>
         *             &lt;enumeration value="LONGTON"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="piece-package-type" type="{http://www.w3.org/2001/XMLSchema}NCName" />
         *       &lt;attribute name="piece-length-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="piece-width-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="piece-height-cm" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="piece-weight-kg" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *       &lt;attribute name="product-type" type="{http://www.w3.org/2001/XMLSchema}NCName" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reefer",
            "cargoLots"
        })
        public static class Item {

            protected TReeferRequirements reefer;
            @XmlElement(name = "cargo-lots")
            protected TBillOfLading.Items.Item.CargoLots cargoLots;
            @XmlAttribute(name = "bulk-unit")
            protected String bulkUnit;
            @XmlAttribute(name = "commodity-id", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NCName")
            protected String commodityId;
            @XmlAttribute(name = "is-bulk", required = true)
            protected boolean isBulk;
            @XmlAttribute
            protected String nbr;
            @XmlAttribute
            protected BigInteger quantity;
            @XmlAttribute(name = "package-type")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NCName")
            protected String packageType;
            @XmlAttribute(name = "package-length-cm")
            protected BigInteger packageLengthCm;
            @XmlAttribute(name = "package-width-cm")
            protected BigInteger packageWidthCm;
            @XmlAttribute(name = "package-height-cm")
            protected BigInteger packageHeightCm;
            @XmlAttribute(name = "package-weight-kg")
            protected BigDecimal packageWeightKg;
            @XmlAttribute(name = "piece-quantity")
            protected BigInteger pieceQuantity;
            @XmlAttribute(name = "piece-is-bulk")
            protected Boolean pieceIsBulk;
            @XmlAttribute(name = "piece-bulk-unit")
            protected String pieceBulkUnit;
            @XmlAttribute(name = "piece-package-type")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NCName")
            protected String piecePackageType;
            @XmlAttribute(name = "piece-length-cm")
            protected BigInteger pieceLengthCm;
            @XmlAttribute(name = "piece-width-cm")
            protected BigInteger pieceWidthCm;
            @XmlAttribute(name = "piece-height-cm")
            protected BigInteger pieceHeightCm;
            @XmlAttribute(name = "piece-weight-kg")
            protected BigDecimal pieceWeightKg;
            @XmlAttribute(name = "product-type")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NCName")
            protected String productType;

            /**
             * Gets the value of the reefer property.
             * 
             * @return
             *     possible object is
             *     {@link TReeferRequirements }
             *     
             */
            public TReeferRequirements getReefer() {
                return reefer;
            }

            /**
             * Sets the value of the reefer property.
             * 
             * @param value
             *     allowed object is
             *     {@link TReeferRequirements }
             *     
             */
            public void setReefer(TReeferRequirements value) {
                this.reefer = value;
            }

            /**
             * Gets the value of the cargoLots property.
             * 
             * @return
             *     possible object is
             *     {@link TBillOfLading.Items.Item.CargoLots }
             *     
             */
            public TBillOfLading.Items.Item.CargoLots getCargoLots() {
                return cargoLots;
            }

            /**
             * Sets the value of the cargoLots property.
             * 
             * @param value
             *     allowed object is
             *     {@link TBillOfLading.Items.Item.CargoLots }
             *     
             */
            public void setCargoLots(TBillOfLading.Items.Item.CargoLots value) {
                this.cargoLots = value;
            }

            /**
             * Gets the value of the bulkUnit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBulkUnit() {
                return bulkUnit;
            }

            /**
             * Sets the value of the bulkUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBulkUnit(String value) {
                this.bulkUnit = value;
            }

            /**
             * Gets the value of the commodityId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCommodityId() {
                return commodityId;
            }

            /**
             * Sets the value of the commodityId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCommodityId(String value) {
                this.commodityId = value;
            }

            /**
             * Gets the value of the isBulk property.
             * 
             */
            public boolean isIsBulk() {
                return isBulk;
            }

            /**
             * Sets the value of the isBulk property.
             * 
             */
            public void setIsBulk(boolean value) {
                this.isBulk = value;
            }

            /**
             * Gets the value of the nbr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNbr() {
                return nbr;
            }

            /**
             * Sets the value of the nbr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNbr(String value) {
                this.nbr = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setQuantity(BigInteger value) {
                this.quantity = value;
            }

            /**
             * Gets the value of the packageType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPackageType() {
                return packageType;
            }

            /**
             * Sets the value of the packageType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPackageType(String value) {
                this.packageType = value;
            }

            /**
             * Gets the value of the packageLengthCm property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPackageLengthCm() {
                return packageLengthCm;
            }

            /**
             * Sets the value of the packageLengthCm property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPackageLengthCm(BigInteger value) {
                this.packageLengthCm = value;
            }

            /**
             * Gets the value of the packageWidthCm property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPackageWidthCm() {
                return packageWidthCm;
            }

            /**
             * Sets the value of the packageWidthCm property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPackageWidthCm(BigInteger value) {
                this.packageWidthCm = value;
            }

            /**
             * Gets the value of the packageHeightCm property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPackageHeightCm() {
                return packageHeightCm;
            }

            /**
             * Sets the value of the packageHeightCm property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPackageHeightCm(BigInteger value) {
                this.packageHeightCm = value;
            }

            /**
             * Gets the value of the packageWeightKg property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPackageWeightKg() {
                return packageWeightKg;
            }

            /**
             * Sets the value of the packageWeightKg property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPackageWeightKg(BigDecimal value) {
                this.packageWeightKg = value;
            }

            /**
             * Gets the value of the pieceQuantity property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPieceQuantity() {
                return pieceQuantity;
            }

            /**
             * Sets the value of the pieceQuantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPieceQuantity(BigInteger value) {
                this.pieceQuantity = value;
            }

            /**
             * Gets the value of the pieceIsBulk property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isPieceIsBulk() {
                return pieceIsBulk;
            }

            /**
             * Sets the value of the pieceIsBulk property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setPieceIsBulk(Boolean value) {
                this.pieceIsBulk = value;
            }

            /**
             * Gets the value of the pieceBulkUnit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPieceBulkUnit() {
                return pieceBulkUnit;
            }

            /**
             * Sets the value of the pieceBulkUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPieceBulkUnit(String value) {
                this.pieceBulkUnit = value;
            }

            /**
             * Gets the value of the piecePackageType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPiecePackageType() {
                return piecePackageType;
            }

            /**
             * Sets the value of the piecePackageType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPiecePackageType(String value) {
                this.piecePackageType = value;
            }

            /**
             * Gets the value of the pieceLengthCm property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPieceLengthCm() {
                return pieceLengthCm;
            }

            /**
             * Sets the value of the pieceLengthCm property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPieceLengthCm(BigInteger value) {
                this.pieceLengthCm = value;
            }

            /**
             * Gets the value of the pieceWidthCm property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPieceWidthCm() {
                return pieceWidthCm;
            }

            /**
             * Sets the value of the pieceWidthCm property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPieceWidthCm(BigInteger value) {
                this.pieceWidthCm = value;
            }

            /**
             * Gets the value of the pieceHeightCm property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPieceHeightCm() {
                return pieceHeightCm;
            }

            /**
             * Sets the value of the pieceHeightCm property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPieceHeightCm(BigInteger value) {
                this.pieceHeightCm = value;
            }

            /**
             * Gets the value of the pieceWeightKg property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPieceWeightKg() {
                return pieceWeightKg;
            }

            /**
             * Sets the value of the pieceWeightKg property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPieceWeightKg(BigDecimal value) {
                this.pieceWeightKg = value;
            }

            /**
             * Gets the value of the productType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductType() {
                return productType;
            }

            /**
             * Sets the value of the productType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductType(String value) {
                this.productType = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="cargo-lot" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="unit-id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
             *                 &lt;attribute name="unit-key" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="quantity" type="{http://www.w3.org/2001/XMLSchema}integer" />
             *                 &lt;attribute name="quantity-manifiested" type="{http://www.w3.org/2001/XMLSchema}integer" />
             *                 &lt;attribute name="quantity-discrepency" type="{http://www.w3.org/2001/XMLSchema}integer" />
             *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}NCName" />
             *                 &lt;attribute name="brand" type="{http://www.w3.org/2001/XMLSchema}NCName" />
             *                 &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}NCName" />
             *                 &lt;attribute name="model" type="{http://www.w3.org/2001/XMLSchema}NCName" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="update-mode" type="{http://www.navis.com/argo}tUpdateMode" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cargoLot"
            })
            public static class CargoLots {

                @XmlElement(name = "cargo-lot")
                protected List<TBillOfLading.Items.Item.CargoLots.CargoLot> cargoLot;
                @XmlAttribute(name = "update-mode")
                protected TUpdateMode updateMode;

                /**
                 * Gets the value of the cargoLot property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the cargoLot property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCargoLot().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TBillOfLading.Items.Item.CargoLots.CargoLot }
                 * 
                 * 
                 */
                public List<TBillOfLading.Items.Item.CargoLots.CargoLot> getCargoLot() {
                    if (cargoLot == null) {
                        cargoLot = new ArrayList<TBillOfLading.Items.Item.CargoLots.CargoLot>();
                    }
                    return this.cargoLot;
                }

                /**
                 * Gets the value of the updateMode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TUpdateMode }
                 *     
                 */
                public TUpdateMode getUpdateMode() {
                    return updateMode;
                }

                /**
                 * Sets the value of the updateMode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TUpdateMode }
                 *     
                 */
                public void setUpdateMode(TUpdateMode value) {
                    this.updateMode = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="unit-id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
                 *       &lt;attribute name="unit-key" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="quantity" type="{http://www.w3.org/2001/XMLSchema}integer" />
                 *       &lt;attribute name="quantity-manifiested" type="{http://www.w3.org/2001/XMLSchema}integer" />
                 *       &lt;attribute name="quantity-discrepency" type="{http://www.w3.org/2001/XMLSchema}integer" />
                 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}NCName" />
                 *       &lt;attribute name="brand" type="{http://www.w3.org/2001/XMLSchema}NCName" />
                 *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}NCName" />
                 *       &lt;attribute name="model" type="{http://www.w3.org/2001/XMLSchema}NCName" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class CargoLot {

                    @XmlAttribute(name = "unit-id", required = true)
                    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                    @XmlSchemaType(name = "NCName")
                    protected String unitId;
                    @XmlAttribute(name = "unit-key")
                    protected String unitKey;
                    @XmlAttribute
                    protected BigInteger quantity;
                    @XmlAttribute(name = "quantity-manifiested")
                    protected BigInteger quantityManifiested;
                    @XmlAttribute(name = "quantity-discrepency")
                    protected BigInteger quantityDiscrepency;
                    @XmlAttribute
                    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                    @XmlSchemaType(name = "NCName")
                    protected String id;
                    @XmlAttribute
                    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                    @XmlSchemaType(name = "NCName")
                    protected String brand;
                    @XmlAttribute
                    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                    @XmlSchemaType(name = "NCName")
                    protected String color;
                    @XmlAttribute
                    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                    @XmlSchemaType(name = "NCName")
                    protected String model;

                    /**
                     * Gets the value of the unitId property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getUnitId() {
                        return unitId;
                    }

                    /**
                     * Sets the value of the unitId property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setUnitId(String value) {
                        this.unitId = value;
                    }

                    /**
                     * Gets the value of the unitKey property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getUnitKey() {
                        return unitKey;
                    }

                    /**
                     * Sets the value of the unitKey property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setUnitKey(String value) {
                        this.unitKey = value;
                    }

                    /**
                     * Gets the value of the quantity property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getQuantity() {
                        return quantity;
                    }

                    /**
                     * Sets the value of the quantity property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setQuantity(BigInteger value) {
                        this.quantity = value;
                    }

                    /**
                     * Gets the value of the quantityManifiested property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getQuantityManifiested() {
                        return quantityManifiested;
                    }

                    /**
                     * Sets the value of the quantityManifiested property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setQuantityManifiested(BigInteger value) {
                        this.quantityManifiested = value;
                    }

                    /**
                     * Gets the value of the quantityDiscrepency property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getQuantityDiscrepency() {
                        return quantityDiscrepency;
                    }

                    /**
                     * Sets the value of the quantityDiscrepency property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setQuantityDiscrepency(BigInteger value) {
                        this.quantityDiscrepency = value;
                    }

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setId(String value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the brand property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBrand() {
                        return brand;
                    }

                    /**
                     * Sets the value of the brand property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBrand(String value) {
                        this.brand = value;
                    }

                    /**
                     * Gets the value of the color property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getColor() {
                        return color;
                    }

                    /**
                     * Sets the value of the color property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setColor(String value) {
                        this.color = value;
                    }

                    /**
                     * Gets the value of the model property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getModel() {
                        return model;
                    }

                    /**
                     * Sets the value of the model property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setModel(String value) {
                        this.model = value;
                    }

                }

            }

        }

    }

}
