//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Used to identify a chassis entity.
 * 
 * <p>Java class for tChassis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tChassis">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.navis.com/argo}tEquipment">
 *       &lt;attribute name="license-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="license-state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fed-inspect-exp" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="state-inspect-exp" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="axle-count" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="is-chassis-triaxle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fits-20" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fits-24" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fits-30" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fits-40" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fits-45" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fits-48" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fits-53" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tChassis")
public class TChassis
    extends TEquipment
{

    @XmlAttribute(name = "license-nbr")
    protected String licenseNbr;
    @XmlAttribute(name = "license-state")
    protected String licenseState;
    @XmlAttribute(name = "fed-inspect-exp")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fedInspectExp;
    @XmlAttribute(name = "state-inspect-exp")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar stateInspectExp;
    @XmlAttribute(name = "axle-count")
    protected BigInteger axleCount;
    @XmlAttribute(name = "is-chassis-triaxle")
    protected String isChassisTriaxle;
    @XmlAttribute(name = "fits-20")
    protected String fits20;
    @XmlAttribute(name = "fits-24")
    protected String fits24;
    @XmlAttribute(name = "fits-30")
    protected String fits30;
    @XmlAttribute(name = "fits-40")
    protected String fits40;
    @XmlAttribute(name = "fits-45")
    protected String fits45;
    @XmlAttribute(name = "fits-48")
    protected String fits48;
    @XmlAttribute(name = "fits-53")
    protected String fits53;

    /**
     * Gets the value of the licenseNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseNbr() {
        return licenseNbr;
    }

    /**
     * Sets the value of the licenseNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseNbr(String value) {
        this.licenseNbr = value;
    }

    /**
     * Gets the value of the licenseState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseState() {
        return licenseState;
    }

    /**
     * Sets the value of the licenseState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseState(String value) {
        this.licenseState = value;
    }

    /**
     * Gets the value of the fedInspectExp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFedInspectExp() {
        return fedInspectExp;
    }

    /**
     * Sets the value of the fedInspectExp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFedInspectExp(XMLGregorianCalendar value) {
        this.fedInspectExp = value;
    }

    /**
     * Gets the value of the stateInspectExp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStateInspectExp() {
        return stateInspectExp;
    }

    /**
     * Sets the value of the stateInspectExp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStateInspectExp(XMLGregorianCalendar value) {
        this.stateInspectExp = value;
    }

    /**
     * Gets the value of the axleCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAxleCount() {
        return axleCount;
    }

    /**
     * Sets the value of the axleCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAxleCount(BigInteger value) {
        this.axleCount = value;
    }

    /**
     * Gets the value of the isChassisTriaxle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsChassisTriaxle() {
        return isChassisTriaxle;
    }

    /**
     * Sets the value of the isChassisTriaxle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsChassisTriaxle(String value) {
        this.isChassisTriaxle = value;
    }

    /**
     * Gets the value of the fits20 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFits20() {
        return fits20;
    }

    /**
     * Sets the value of the fits20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFits20(String value) {
        this.fits20 = value;
    }

    /**
     * Gets the value of the fits24 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFits24() {
        return fits24;
    }

    /**
     * Sets the value of the fits24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFits24(String value) {
        this.fits24 = value;
    }

    /**
     * Gets the value of the fits30 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFits30() {
        return fits30;
    }

    /**
     * Sets the value of the fits30 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFits30(String value) {
        this.fits30 = value;
    }

    /**
     * Gets the value of the fits40 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFits40() {
        return fits40;
    }

    /**
     * Sets the value of the fits40 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFits40(String value) {
        this.fits40 = value;
    }

    /**
     * Gets the value of the fits45 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFits45() {
        return fits45;
    }

    /**
     * Sets the value of the fits45 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFits45(String value) {
        this.fits45 = value;
    }

    /**
     * Gets the value of the fits48 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFits48() {
        return fits48;
    }

    /**
     * Sets the value of the fits48 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFits48(String value) {
        this.fits48 = value;
    }

    /**
     * Gets the value of the fits53 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFits53() {
        return fits53;
    }

    /**
     * Sets the value of the fits53 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFits53(String value) {
        this.fits53 = value;
    }

}
