//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Crane Delay Type
 * 
 * <p>Java class for tCraneDelayType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCraneDelayType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sparcs-code" type="{http://www.navis.com/argo}tSparcsCraneCodes" />
 *       &lt;attribute name="is-dispatch-stopped" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="is-for-shift" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="is-for-queue" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="is-for-n4rdt" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="is-stpd-by-new-work" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="is-stops-at-end-time" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="default-duration" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="delay-category" type="{http://www.navis.com/argo}tCraneDelayCategory" />
 *       &lt;attribute name="life-cycle-state" type="{http://www.navis.com/argo}tLifeCycleStateType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCraneDelayType")
public class TCraneDelayType {

    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected String description;
    @XmlAttribute(name = "sparcs-code")
    protected TSparcsCraneCodes sparcsCode;
    @XmlAttribute(name = "is-dispatch-stopped")
    protected Boolean isDispatchStopped;
    @XmlAttribute(name = "is-for-shift")
    protected Boolean isForShift;
    @XmlAttribute(name = "is-for-queue")
    protected Boolean isForQueue;
    @XmlAttribute(name = "is-for-n4rdt")
    protected Boolean isForN4Rdt;
    @XmlAttribute(name = "is-stpd-by-new-work")
    protected Boolean isStpdByNewWork;
    @XmlAttribute(name = "is-stops-at-end-time")
    protected Boolean isStopsAtEndTime;
    @XmlAttribute(name = "default-duration")
    protected Long defaultDuration;
    @XmlAttribute(name = "delay-category")
    protected TCraneDelayCategory delayCategory;
    @XmlAttribute(name = "life-cycle-state")
    protected TLifeCycleStateType lifeCycleState;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the sparcsCode property.
     * 
     * @return
     *     possible object is
     *     {@link TSparcsCraneCodes }
     *     
     */
    public TSparcsCraneCodes getSparcsCode() {
        return sparcsCode;
    }

    /**
     * Sets the value of the sparcsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSparcsCraneCodes }
     *     
     */
    public void setSparcsCode(TSparcsCraneCodes value) {
        this.sparcsCode = value;
    }

    /**
     * Gets the value of the isDispatchStopped property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDispatchStopped() {
        return isDispatchStopped;
    }

    /**
     * Sets the value of the isDispatchStopped property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDispatchStopped(Boolean value) {
        this.isDispatchStopped = value;
    }

    /**
     * Gets the value of the isForShift property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsForShift() {
        return isForShift;
    }

    /**
     * Sets the value of the isForShift property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsForShift(Boolean value) {
        this.isForShift = value;
    }

    /**
     * Gets the value of the isForQueue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsForQueue() {
        return isForQueue;
    }

    /**
     * Sets the value of the isForQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsForQueue(Boolean value) {
        this.isForQueue = value;
    }

    /**
     * Gets the value of the isForN4Rdt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsForN4Rdt() {
        return isForN4Rdt;
    }

    /**
     * Sets the value of the isForN4Rdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsForN4Rdt(Boolean value) {
        this.isForN4Rdt = value;
    }

    /**
     * Gets the value of the isStpdByNewWork property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsStpdByNewWork() {
        return isStpdByNewWork;
    }

    /**
     * Sets the value of the isStpdByNewWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsStpdByNewWork(Boolean value) {
        this.isStpdByNewWork = value;
    }

    /**
     * Gets the value of the isStopsAtEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsStopsAtEndTime() {
        return isStopsAtEndTime;
    }

    /**
     * Sets the value of the isStopsAtEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsStopsAtEndTime(Boolean value) {
        this.isStopsAtEndTime = value;
    }

    /**
     * Gets the value of the defaultDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDefaultDuration() {
        return defaultDuration;
    }

    /**
     * Sets the value of the defaultDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDefaultDuration(Long value) {
        this.defaultDuration = value;
    }

    /**
     * Gets the value of the delayCategory property.
     * 
     * @return
     *     possible object is
     *     {@link TCraneDelayCategory }
     *     
     */
    public TCraneDelayCategory getDelayCategory() {
        return delayCategory;
    }

    /**
     * Sets the value of the delayCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCraneDelayCategory }
     *     
     */
    public void setDelayCategory(TCraneDelayCategory value) {
        this.delayCategory = value;
    }

    /**
     * Gets the value of the lifeCycleState property.
     * 
     * @return
     *     possible object is
     *     {@link TLifeCycleStateType }
     *     
     */
    public TLifeCycleStateType getLifeCycleState() {
        return lifeCycleState;
    }

    /**
     * Sets the value of the lifeCycleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLifeCycleStateType }
     *     
     */
    public void setLifeCycleState(TLifeCycleStateType value) {
        this.lifeCycleState = value;
    }

}
