//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tEquipNominalLength.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tEquipNominalLength">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NOM20"/>
 *     &lt;enumeration value="NOM22"/>
 *     &lt;enumeration value="NOM24"/>
 *     &lt;enumeration value="NOM30"/>
 *     &lt;enumeration value="NOM32"/>
 *     &lt;enumeration value="NOM40"/>
 *     &lt;enumeration value="NOM42"/>
 *     &lt;enumeration value="NOM45"/>
 *     &lt;enumeration value="NOM48"/>
 *     &lt;enumeration value="NOM51"/>
 *     &lt;enumeration value="NOM53"/>
 *     &lt;enumeration value="NOM546"/>
 *     &lt;enumeration value="NOM60"/>
 *     &lt;enumeration value="NOMXX"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tEquipNominalLength")
@XmlEnum
public enum TEquipNominalLength {

    @XmlEnumValue("NOM20")
    NOM_20("NOM20"),
    @XmlEnumValue("NOM22")
    NOM_22("NOM22"),
    @XmlEnumValue("NOM24")
    NOM_24("NOM24"),
    @XmlEnumValue("NOM30")
    NOM_30("NOM30"),
    @XmlEnumValue("NOM32")
    NOM_32("NOM32"),
    @XmlEnumValue("NOM40")
    NOM_40("NOM40"),
    @XmlEnumValue("NOM42")
    NOM_42("NOM42"),
    @XmlEnumValue("NOM45")
    NOM_45("NOM45"),
    @XmlEnumValue("NOM48")
    NOM_48("NOM48"),
    @XmlEnumValue("NOM51")
    NOM_51("NOM51"),
    @XmlEnumValue("NOM53")
    NOM_53("NOM53"),
    @XmlEnumValue("NOM546")
    NOM_546("NOM546"),
    @XmlEnumValue("NOM60")
    NOM_60("NOM60"),
    NOMXX("NOMXX");
    private final String value;

    TEquipNominalLength(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TEquipNominalLength fromValue(String v) {
        for (TEquipNominalLength c: TEquipNominalLength.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
