//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Equipment Type Definition.
 * 
 * <p>Java class for tEquipmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEquipmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="archetype-def" type="{http://www.navis.com/argo}tEquipmentType" minOccurs="0"/>
 *         &lt;element name="chassis-properties" type="{http://www.navis.com/argo}tChassisProperties" minOccurs="0"/>
 *         &lt;element name="restrictions" type="{http://www.navis.com/argo}tEquipTypeRestrictions" minOccurs="0"/>
 *         &lt;element name="reefer" type="{http://www.navis.com/argo}tBaseReefer" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="archetype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="class" type="{http://www.navis.com/argo}tEquipmentClass" />
 *       &lt;attribute name="iso-group" type="{http://www.navis.com/argo}tIsoGroup" />
 *       &lt;attribute name="length-mm" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="height-mm" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="width-mm" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="tare-weight-kg" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="safe-weight-kg" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pict-id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="life-cycle-state" type="{http://www.navis.com/argo}tLifeCycleStateType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEquipmentType", propOrder = {
    "archetypeDef",
    "chassisProperties",
    "restrictions",
    "reefer"
})
public class TEquipmentType {

    @XmlElement(name = "archetype-def")
    protected TEquipmentType archetypeDef;
    @XmlElement(name = "chassis-properties")
    protected TChassisProperties chassisProperties;
    protected TEquipTypeRestrictions restrictions;
    protected TBaseReefer reefer;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected String archetype;
    @XmlAttribute(name = "class")
    protected TEquipmentClass clazz;
    @XmlAttribute(name = "iso-group")
    protected TIsoGroup isoGroup;
    @XmlAttribute(name = "length-mm")
    protected Integer lengthMm;
    @XmlAttribute(name = "height-mm")
    protected Integer heightMm;
    @XmlAttribute(name = "width-mm")
    protected Integer widthMm;
    @XmlAttribute(name = "tare-weight-kg")
    protected Double tareWeightKg;
    @XmlAttribute(name = "safe-weight-kg")
    protected Double safeWeightKg;
    @XmlAttribute
    protected String description;
    @XmlAttribute(name = "pict-id")
    protected Integer pictId;
    @XmlAttribute(name = "life-cycle-state")
    protected TLifeCycleStateType lifeCycleState;

    /**
     * Gets the value of the archetypeDef property.
     * 
     * @return
     *     possible object is
     *     {@link TEquipmentType }
     *     
     */
    public TEquipmentType getArchetypeDef() {
        return archetypeDef;
    }

    /**
     * Sets the value of the archetypeDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEquipmentType }
     *     
     */
    public void setArchetypeDef(TEquipmentType value) {
        this.archetypeDef = value;
    }

    /**
     * Gets the value of the chassisProperties property.
     * 
     * @return
     *     possible object is
     *     {@link TChassisProperties }
     *     
     */
    public TChassisProperties getChassisProperties() {
        return chassisProperties;
    }

    /**
     * Sets the value of the chassisProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link TChassisProperties }
     *     
     */
    public void setChassisProperties(TChassisProperties value) {
        this.chassisProperties = value;
    }

    /**
     * Gets the value of the restrictions property.
     * 
     * @return
     *     possible object is
     *     {@link TEquipTypeRestrictions }
     *     
     */
    public TEquipTypeRestrictions getRestrictions() {
        return restrictions;
    }

    /**
     * Sets the value of the restrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEquipTypeRestrictions }
     *     
     */
    public void setRestrictions(TEquipTypeRestrictions value) {
        this.restrictions = value;
    }

    /**
     * Gets the value of the reefer property.
     * 
     * @return
     *     possible object is
     *     {@link TBaseReefer }
     *     
     */
    public TBaseReefer getReefer() {
        return reefer;
    }

    /**
     * Sets the value of the reefer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBaseReefer }
     *     
     */
    public void setReefer(TBaseReefer value) {
        this.reefer = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the archetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchetype() {
        return archetype;
    }

    /**
     * Sets the value of the archetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchetype(String value) {
        this.archetype = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link TEquipmentClass }
     *     
     */
    public TEquipmentClass getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEquipmentClass }
     *     
     */
    public void setClazz(TEquipmentClass value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the isoGroup property.
     * 
     * @return
     *     possible object is
     *     {@link TIsoGroup }
     *     
     */
    public TIsoGroup getIsoGroup() {
        return isoGroup;
    }

    /**
     * Sets the value of the isoGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIsoGroup }
     *     
     */
    public void setIsoGroup(TIsoGroup value) {
        this.isoGroup = value;
    }

    /**
     * Gets the value of the lengthMm property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLengthMm() {
        return lengthMm;
    }

    /**
     * Sets the value of the lengthMm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLengthMm(Integer value) {
        this.lengthMm = value;
    }

    /**
     * Gets the value of the heightMm property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHeightMm() {
        return heightMm;
    }

    /**
     * Sets the value of the heightMm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeightMm(Integer value) {
        this.heightMm = value;
    }

    /**
     * Gets the value of the widthMm property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWidthMm() {
        return widthMm;
    }

    /**
     * Sets the value of the widthMm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWidthMm(Integer value) {
        this.widthMm = value;
    }

    /**
     * Gets the value of the tareWeightKg property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTareWeightKg() {
        return tareWeightKg;
    }

    /**
     * Sets the value of the tareWeightKg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTareWeightKg(Double value) {
        this.tareWeightKg = value;
    }

    /**
     * Gets the value of the safeWeightKg property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSafeWeightKg() {
        return safeWeightKg;
    }

    /**
     * Sets the value of the safeWeightKg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSafeWeightKg(Double value) {
        this.safeWeightKg = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the pictId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPictId() {
        return pictId;
    }

    /**
     * Sets the value of the pictId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPictId(Integer value) {
        this.pictId = value;
    }

    /**
     * Gets the value of the lifeCycleState property.
     * 
     * @return
     *     possible object is
     *     {@link TLifeCycleStateType }
     *     
     */
    public TLifeCycleStateType getLifeCycleState() {
        return lifeCycleState;
    }

    /**
     * Sets the value of the lifeCycleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLifeCycleStateType }
     *     
     */
    public void setLifeCycleState(TLifeCycleStateType value) {
        this.lifeCycleState = value;
    }

}
