//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Equipment Serial Range.
 * 
 * <p>Java class for tEquipSerialRange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEquipSerialRange">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="restrictions" type="{http://www.navis.com/argo}tEquipTypeRestrictions" minOccurs="0"/>
 *         &lt;element name="reefer" type="{http://www.navis.com/argo}tBaseReefer" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="prefix" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="equip-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="iso-group" type="{http://www.navis.com/argo}tIsoGroup" />
 *       &lt;attribute name="starting-serial-nbr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="length-mm" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="height-mm" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="width-mm" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="tare-weight-kg" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="ending-serial-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="life-cycle-state" type="{http://www.navis.com/argo}tLifeCycleStateType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEquipSerialRange", propOrder = {
    "restrictions",
    "reefer"
})
public class TEquipSerialRange {

    protected TEquipTypeRestrictions restrictions;
    protected TBaseReefer reefer;
    @XmlAttribute(required = true)
    protected String prefix;
    @XmlAttribute(name = "equip-type")
    protected String equipType;
    @XmlAttribute(name = "iso-group")
    protected TIsoGroup isoGroup;
    @XmlAttribute(name = "starting-serial-nbr", required = true)
    protected String startingSerialNbr;
    @XmlAttribute(name = "length-mm")
    protected Integer lengthMm;
    @XmlAttribute(name = "height-mm")
    protected Integer heightMm;
    @XmlAttribute(name = "width-mm")
    protected Integer widthMm;
    @XmlAttribute(name = "tare-weight-kg")
    protected Double tareWeightKg;
    @XmlAttribute(name = "ending-serial-nbr")
    protected String endingSerialNbr;
    @XmlAttribute(name = "life-cycle-state")
    protected TLifeCycleStateType lifeCycleState;

    /**
     * Gets the value of the restrictions property.
     * 
     * @return
     *     possible object is
     *     {@link TEquipTypeRestrictions }
     *     
     */
    public TEquipTypeRestrictions getRestrictions() {
        return restrictions;
    }

    /**
     * Sets the value of the restrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEquipTypeRestrictions }
     *     
     */
    public void setRestrictions(TEquipTypeRestrictions value) {
        this.restrictions = value;
    }

    /**
     * Gets the value of the reefer property.
     * 
     * @return
     *     possible object is
     *     {@link TBaseReefer }
     *     
     */
    public TBaseReefer getReefer() {
        return reefer;
    }

    /**
     * Sets the value of the reefer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBaseReefer }
     *     
     */
    public void setReefer(TBaseReefer value) {
        this.reefer = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the equipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipType() {
        return equipType;
    }

    /**
     * Sets the value of the equipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipType(String value) {
        this.equipType = value;
    }

    /**
     * Gets the value of the isoGroup property.
     * 
     * @return
     *     possible object is
     *     {@link TIsoGroup }
     *     
     */
    public TIsoGroup getIsoGroup() {
        return isoGroup;
    }

    /**
     * Sets the value of the isoGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIsoGroup }
     *     
     */
    public void setIsoGroup(TIsoGroup value) {
        this.isoGroup = value;
    }

    /**
     * Gets the value of the startingSerialNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartingSerialNbr() {
        return startingSerialNbr;
    }

    /**
     * Sets the value of the startingSerialNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartingSerialNbr(String value) {
        this.startingSerialNbr = value;
    }

    /**
     * Gets the value of the lengthMm property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLengthMm() {
        return lengthMm;
    }

    /**
     * Sets the value of the lengthMm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLengthMm(Integer value) {
        this.lengthMm = value;
    }

    /**
     * Gets the value of the heightMm property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHeightMm() {
        return heightMm;
    }

    /**
     * Sets the value of the heightMm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeightMm(Integer value) {
        this.heightMm = value;
    }

    /**
     * Gets the value of the widthMm property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWidthMm() {
        return widthMm;
    }

    /**
     * Sets the value of the widthMm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWidthMm(Integer value) {
        this.widthMm = value;
    }

    /**
     * Gets the value of the tareWeightKg property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTareWeightKg() {
        return tareWeightKg;
    }

    /**
     * Sets the value of the tareWeightKg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTareWeightKg(Double value) {
        this.tareWeightKg = value;
    }

    /**
     * Gets the value of the endingSerialNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndingSerialNbr() {
        return endingSerialNbr;
    }

    /**
     * Sets the value of the endingSerialNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndingSerialNbr(String value) {
        this.endingSerialNbr = value;
    }

    /**
     * Gets the value of the lifeCycleState property.
     * 
     * @return
     *     possible object is
     *     {@link TLifeCycleStateType }
     *     
     */
    public TLifeCycleStateType getLifeCycleState() {
        return lifeCycleState;
    }

    /**
     * Sets the value of the lifeCycleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLifeCycleStateType }
     *     
     */
    public void setLifeCycleState(TLifeCycleStateType value) {
        this.lifeCycleState = value;
    }

}
