//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Gate Lane
 * 
 * <p>Java class for tGateLane complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tGateLane">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gate-lane-printers" type="{http://www.navis.com/argo}tGateLanePrinters" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="class" use="required" type="{http://www.navis.com/argo}tGateLaneClass" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="truck-license-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pedestal-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="needs-appointment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="has-scale" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="is-closed" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tGateLane", propOrder = {
    "gateLanePrinters"
})
public class TGateLane {

    @XmlElement(name = "gate-lane-printers")
    protected TGateLanePrinters gateLanePrinters;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(name = "class", required = true)
    protected TGateLaneClass clazz;
    @XmlAttribute
    protected String description;
    @XmlAttribute(name = "truck-license-nbr")
    protected String truckLicenseNbr;
    @XmlAttribute(name = "pedestal-id")
    protected String pedestalId;
    @XmlAttribute(name = "needs-appointment")
    protected String needsAppointment;
    @XmlAttribute(name = "has-scale")
    protected String hasScale;
    @XmlAttribute(name = "is-closed")
    protected String isClosed;

    /**
     * Gets the value of the gateLanePrinters property.
     * 
     * @return
     *     possible object is
     *     {@link TGateLanePrinters }
     *     
     */
    public TGateLanePrinters getGateLanePrinters() {
        return gateLanePrinters;
    }

    /**
     * Sets the value of the gateLanePrinters property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGateLanePrinters }
     *     
     */
    public void setGateLanePrinters(TGateLanePrinters value) {
        this.gateLanePrinters = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link TGateLaneClass }
     *     
     */
    public TGateLaneClass getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGateLaneClass }
     *     
     */
    public void setClazz(TGateLaneClass value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the truckLicenseNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTruckLicenseNbr() {
        return truckLicenseNbr;
    }

    /**
     * Sets the value of the truckLicenseNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTruckLicenseNbr(String value) {
        this.truckLicenseNbr = value;
    }

    /**
     * Gets the value of the pedestalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPedestalId() {
        return pedestalId;
    }

    /**
     * Sets the value of the pedestalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPedestalId(String value) {
        this.pedestalId = value;
    }

    /**
     * Gets the value of the needsAppointment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeedsAppointment() {
        return needsAppointment;
    }

    /**
     * Sets the value of the needsAppointment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeedsAppointment(String value) {
        this.needsAppointment = value;
    }

    /**
     * Gets the value of the hasScale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasScale() {
        return hasScale;
    }

    /**
     * Sets the value of the hasScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasScale(String value) {
        this.hasScale = value;
    }

    /**
     * Gets the value of the isClosed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsClosed() {
        return isClosed;
    }

    /**
     * Sets the value of the isClosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsClosed(String value) {
        this.isClosed = value;
    }

}
