//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for tGuarantee complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tGuarantee">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="billToInformation" type="{http://www.navis.com/argo}tBillToInformation" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="action" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="n4-user-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="applied-to-class" type="{http://www.navis.com/argo}tGuaranteeAppliedToClass" />
 *       &lt;attribute name="applied-to-natural-key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="applied-to-primary-key" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="ext-user-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ext-user-contact-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ext-user-address1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ext-user-address2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ext-user-address3" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ext-user-city" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ext-user-state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ext-user-country" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ext-user-telephone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ext-user-fax" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ext-user-email-address" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.navis.com/argo}tGuaranteeType" />
 *       &lt;attribute name="override-value-type" type="{http://www.navis.com/argo}tGuaranteeOverrideType" />
 *       &lt;attribute name="start-day" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="end-day" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="quantity" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="notes" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="voided-expired-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="authorization-expiration" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="customer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="customer-biz-role" type="{http://www.navis.com/argo}tBizRole" />
 *       &lt;attribute name="waiver-expiration-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="customer-reference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tGuarantee", propOrder = {
    "billToInformation"
})
public class TGuarantee {

    protected TBillToInformation billToInformation;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String action;
    @XmlAttribute(name = "n4-user-id")
    protected String n4UserId;
    @XmlAttribute(name = "applied-to-class")
    protected TGuaranteeAppliedToClass appliedToClass;
    @XmlAttribute(name = "applied-to-natural-key")
    protected String appliedToNaturalKey;
    @XmlAttribute(name = "applied-to-primary-key")
    protected Long appliedToPrimaryKey;
    @XmlAttribute(name = "ext-user-id")
    protected String extUserId;
    @XmlAttribute(name = "ext-user-contact-name")
    protected String extUserContactName;
    @XmlAttribute(name = "ext-user-address1")
    protected String extUserAddress1;
    @XmlAttribute(name = "ext-user-address2")
    protected String extUserAddress2;
    @XmlAttribute(name = "ext-user-address3")
    protected String extUserAddress3;
    @XmlAttribute(name = "ext-user-city")
    protected String extUserCity;
    @XmlAttribute(name = "ext-user-state")
    protected String extUserState;
    @XmlAttribute(name = "ext-user-country")
    protected String extUserCountry;
    @XmlAttribute(name = "ext-user-telephone")
    protected String extUserTelephone;
    @XmlAttribute(name = "ext-user-fax")
    protected String extUserFax;
    @XmlAttribute(name = "ext-user-email-address")
    protected String extUserEmailAddress;
    @XmlAttribute
    protected TGuaranteeType type;
    @XmlAttribute(name = "override-value-type")
    protected TGuaranteeOverrideType overrideValueType;
    @XmlAttribute(name = "start-day")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDay;
    @XmlAttribute(name = "end-day")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDay;
    @XmlAttribute
    protected Double quantity;
    @XmlAttribute
    protected Double amount;
    @XmlAttribute
    protected String notes;
    @XmlAttribute(name = "voided-expired-date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar voidedExpiredDate;
    @XmlAttribute(name = "authorization-expiration")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar authorizationExpiration;
    @XmlAttribute
    protected String customer;
    @XmlAttribute(name = "customer-biz-role")
    protected TBizRole customerBizRole;
    @XmlAttribute(name = "waiver-expiration-date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar waiverExpirationDate;
    @XmlAttribute(name = "customer-reference")
    protected String customerReference;

    /**
     * Gets the value of the billToInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TBillToInformation }
     *     
     */
    public TBillToInformation getBillToInformation() {
        return billToInformation;
    }

    /**
     * Sets the value of the billToInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBillToInformation }
     *     
     */
    public void setBillToInformation(TBillToInformation value) {
        this.billToInformation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the n4UserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN4UserId() {
        return n4UserId;
    }

    /**
     * Sets the value of the n4UserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN4UserId(String value) {
        this.n4UserId = value;
    }

    /**
     * Gets the value of the appliedToClass property.
     * 
     * @return
     *     possible object is
     *     {@link TGuaranteeAppliedToClass }
     *     
     */
    public TGuaranteeAppliedToClass getAppliedToClass() {
        return appliedToClass;
    }

    /**
     * Sets the value of the appliedToClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGuaranteeAppliedToClass }
     *     
     */
    public void setAppliedToClass(TGuaranteeAppliedToClass value) {
        this.appliedToClass = value;
    }

    /**
     * Gets the value of the appliedToNaturalKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppliedToNaturalKey() {
        return appliedToNaturalKey;
    }

    /**
     * Sets the value of the appliedToNaturalKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppliedToNaturalKey(String value) {
        this.appliedToNaturalKey = value;
    }

    /**
     * Gets the value of the appliedToPrimaryKey property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAppliedToPrimaryKey() {
        return appliedToPrimaryKey;
    }

    /**
     * Sets the value of the appliedToPrimaryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAppliedToPrimaryKey(Long value) {
        this.appliedToPrimaryKey = value;
    }

    /**
     * Gets the value of the extUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtUserId() {
        return extUserId;
    }

    /**
     * Sets the value of the extUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtUserId(String value) {
        this.extUserId = value;
    }

    /**
     * Gets the value of the extUserContactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtUserContactName() {
        return extUserContactName;
    }

    /**
     * Sets the value of the extUserContactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtUserContactName(String value) {
        this.extUserContactName = value;
    }

    /**
     * Gets the value of the extUserAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtUserAddress1() {
        return extUserAddress1;
    }

    /**
     * Sets the value of the extUserAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtUserAddress1(String value) {
        this.extUserAddress1 = value;
    }

    /**
     * Gets the value of the extUserAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtUserAddress2() {
        return extUserAddress2;
    }

    /**
     * Sets the value of the extUserAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtUserAddress2(String value) {
        this.extUserAddress2 = value;
    }

    /**
     * Gets the value of the extUserAddress3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtUserAddress3() {
        return extUserAddress3;
    }

    /**
     * Sets the value of the extUserAddress3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtUserAddress3(String value) {
        this.extUserAddress3 = value;
    }

    /**
     * Gets the value of the extUserCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtUserCity() {
        return extUserCity;
    }

    /**
     * Sets the value of the extUserCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtUserCity(String value) {
        this.extUserCity = value;
    }

    /**
     * Gets the value of the extUserState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtUserState() {
        return extUserState;
    }

    /**
     * Sets the value of the extUserState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtUserState(String value) {
        this.extUserState = value;
    }

    /**
     * Gets the value of the extUserCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtUserCountry() {
        return extUserCountry;
    }

    /**
     * Sets the value of the extUserCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtUserCountry(String value) {
        this.extUserCountry = value;
    }

    /**
     * Gets the value of the extUserTelephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtUserTelephone() {
        return extUserTelephone;
    }

    /**
     * Sets the value of the extUserTelephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtUserTelephone(String value) {
        this.extUserTelephone = value;
    }

    /**
     * Gets the value of the extUserFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtUserFax() {
        return extUserFax;
    }

    /**
     * Sets the value of the extUserFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtUserFax(String value) {
        this.extUserFax = value;
    }

    /**
     * Gets the value of the extUserEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtUserEmailAddress() {
        return extUserEmailAddress;
    }

    /**
     * Sets the value of the extUserEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtUserEmailAddress(String value) {
        this.extUserEmailAddress = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TGuaranteeType }
     *     
     */
    public TGuaranteeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGuaranteeType }
     *     
     */
    public void setType(TGuaranteeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the overrideValueType property.
     * 
     * @return
     *     possible object is
     *     {@link TGuaranteeOverrideType }
     *     
     */
    public TGuaranteeOverrideType getOverrideValueType() {
        return overrideValueType;
    }

    /**
     * Sets the value of the overrideValueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGuaranteeOverrideType }
     *     
     */
    public void setOverrideValueType(TGuaranteeOverrideType value) {
        this.overrideValueType = value;
    }

    /**
     * Gets the value of the startDay property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDay() {
        return startDay;
    }

    /**
     * Sets the value of the startDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDay(XMLGregorianCalendar value) {
        this.startDay = value;
    }

    /**
     * Gets the value of the endDay property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDay() {
        return endDay;
    }

    /**
     * Sets the value of the endDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDay(XMLGregorianCalendar value) {
        this.endDay = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQuantity(Double value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAmount(Double value) {
        this.amount = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the voidedExpiredDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVoidedExpiredDate() {
        return voidedExpiredDate;
    }

    /**
     * Sets the value of the voidedExpiredDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVoidedExpiredDate(XMLGregorianCalendar value) {
        this.voidedExpiredDate = value;
    }

    /**
     * Gets the value of the authorizationExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAuthorizationExpiration() {
        return authorizationExpiration;
    }

    /**
     * Sets the value of the authorizationExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAuthorizationExpiration(XMLGregorianCalendar value) {
        this.authorizationExpiration = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomer(String value) {
        this.customer = value;
    }

    /**
     * Gets the value of the customerBizRole property.
     * 
     * @return
     *     possible object is
     *     {@link TBizRole }
     *     
     */
    public TBizRole getCustomerBizRole() {
        return customerBizRole;
    }

    /**
     * Sets the value of the customerBizRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBizRole }
     *     
     */
    public void setCustomerBizRole(TBizRole value) {
        this.customerBizRole = value;
    }

    /**
     * Gets the value of the waiverExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWaiverExpirationDate() {
        return waiverExpirationDate;
    }

    /**
     * Sets the value of the waiverExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWaiverExpirationDate(XMLGregorianCalendar value) {
        this.waiverExpirationDate = value;
    }

    /**
     * Gets the value of the customerReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerReference() {
        return customerReference;
    }

    /**
     * Sets the value of the customerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerReference(String value) {
        this.customerReference = value;
    }

}
