//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for tIdo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tIdo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="carrier" type="{http://www.navis.com/argo}tCarrier"/>
 *         &lt;element name="units" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="unit" type="{http://www.navis.com/argo}tIdoUnit" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="line-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="issue-date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="expiry-date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="return-to-location" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="is-doc-provided" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="provided-by" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="provided-date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="carrier-operator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tIdo", propOrder = {
    "carrier",
    "units"
})
public class TIdo {

    @XmlElement(required = true)
    protected TCarrier carrier;
    protected TIdo.Units units;
    @XmlAttribute(required = true)
    protected String number;
    @XmlAttribute(name = "line-id", required = true)
    protected String lineId;
    @XmlAttribute(name = "issue-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar issueDate;
    @XmlAttribute(name = "expiry-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expiryDate;
    @XmlAttribute(name = "return-to-location")
    protected String returnToLocation;
    @XmlAttribute(name = "is-doc-provided")
    protected String isDocProvided;
    @XmlAttribute(name = "provided-by")
    protected String providedBy;
    @XmlAttribute(name = "provided-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar providedDate;
    @XmlAttribute(name = "carrier-operator")
    protected String carrierOperator;

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link TCarrier }
     *     
     */
    public TCarrier getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCarrier }
     *     
     */
    public void setCarrier(TCarrier value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link TIdo.Units }
     *     
     */
    public TIdo.Units getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIdo.Units }
     *     
     */
    public void setUnits(TIdo.Units value) {
        this.units = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the lineId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * Sets the value of the lineId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineId(String value) {
        this.lineId = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDate(XMLGregorianCalendar value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the returnToLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnToLocation() {
        return returnToLocation;
    }

    /**
     * Sets the value of the returnToLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnToLocation(String value) {
        this.returnToLocation = value;
    }

    /**
     * Gets the value of the isDocProvided property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDocProvided() {
        return isDocProvided;
    }

    /**
     * Sets the value of the isDocProvided property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDocProvided(String value) {
        this.isDocProvided = value;
    }

    /**
     * Gets the value of the providedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvidedBy() {
        return providedBy;
    }

    /**
     * Sets the value of the providedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvidedBy(String value) {
        this.providedBy = value;
    }

    /**
     * Gets the value of the providedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProvidedDate() {
        return providedDate;
    }

    /**
     * Sets the value of the providedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProvidedDate(XMLGregorianCalendar value) {
        this.providedDate = value;
    }

    /**
     * Gets the value of the carrierOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierOperator() {
        return carrierOperator;
    }

    /**
     * Sets the value of the carrierOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierOperator(String value) {
        this.carrierOperator = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="unit" type="{http://www.navis.com/argo}tIdoUnit" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unit"
    })
    public static class Units {

        protected List<TIdoUnit> unit;

        /**
         * Gets the value of the unit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the unit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUnit().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TIdoUnit }
         * 
         * 
         */
        public List<TIdoUnit> getUnit() {
            if (unit == null) {
                unit = new ArrayList<TIdoUnit>();
            }
            return this.unit;
        }

    }

}
