//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Master Biz Unit
 * 
 * <p>Java class for tMasterBizUnit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tMasterBizUnit">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.navis.com/argo}tBusinessUnit">
 *       &lt;attribute name="is-eq-operator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="is-eq-owner" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="role" type="{http://www.navis.com/argo}tBizRole" />
 *       &lt;attribute name="life-cycle-state" type="{http://www.navis.com/argo}tLifeCycleStateType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMasterBizUnit")
public class TMasterBizUnit
    extends TBusinessUnit
{

    @XmlAttribute(name = "is-eq-operator")
    protected String isEqOperator;
    @XmlAttribute(name = "is-eq-owner")
    protected String isEqOwner;
    @XmlAttribute
    protected TBizRole role;
    @XmlAttribute(name = "life-cycle-state")
    protected TLifeCycleStateType lifeCycleState;

    /**
     * Gets the value of the isEqOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEqOperator() {
        return isEqOperator;
    }

    /**
     * Sets the value of the isEqOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEqOperator(String value) {
        this.isEqOperator = value;
    }

    /**
     * Gets the value of the isEqOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEqOwner() {
        return isEqOwner;
    }

    /**
     * Sets the value of the isEqOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEqOwner(String value) {
        this.isEqOwner = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link TBizRole }
     *     
     */
    public TBizRole getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBizRole }
     *     
     */
    public void setRole(TBizRole value) {
        this.role = value;
    }

    /**
     * Gets the value of the lifeCycleState property.
     * 
     * @return
     *     possible object is
     *     {@link TLifeCycleStateType }
     *     
     */
    public TLifeCycleStateType getLifeCycleState() {
        return lifeCycleState;
    }

    /**
     * Sets the value of the lifeCycleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLifeCycleStateType }
     *     
     */
    public void setLifeCycleState(TLifeCycleStateType value) {
        this.lifeCycleState = value;
    }

}
