//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Signals the movement of an existing Unit within the facility, or onto a carrier that is at
 *                 the facility.
 *             
 * 
 * <p>Java class for tMove complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tMove">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unit-identity" type="{http://www.navis.com/argo}tUnitIdentity"/>
 *         &lt;element name="to-position" type="{http://www.navis.com/argo}tPosition"/>
 *         &lt;element name="move-details" type="{http://www.navis.com/argo}tMoveDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="move-kind" type="{http://www.navis.com/argo}tMoveKind" />
 *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="is-correction-only" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMove", propOrder = {
    "unitIdentity",
    "toPosition",
    "moveDetails"
})
public class TMove {

    @XmlElement(name = "unit-identity", required = true)
    protected TUnitIdentity unitIdentity;
    @XmlElement(name = "to-position", required = true)
    protected TPosition toPosition;
    @XmlElement(name = "move-details")
    protected TMoveDetails moveDetails;
    @XmlAttribute(name = "move-kind")
    protected TMoveKind moveKind;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlAttribute(name = "is-correction-only")
    protected Boolean isCorrectionOnly;

    /**
     * Gets the value of the unitIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link TUnitIdentity }
     *     
     */
    public TUnitIdentity getUnitIdentity() {
        return unitIdentity;
    }

    /**
     * Sets the value of the unitIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUnitIdentity }
     *     
     */
    public void setUnitIdentity(TUnitIdentity value) {
        this.unitIdentity = value;
    }

    /**
     * Gets the value of the toPosition property.
     * 
     * @return
     *     possible object is
     *     {@link TPosition }
     *     
     */
    public TPosition getToPosition() {
        return toPosition;
    }

    /**
     * Sets the value of the toPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPosition }
     *     
     */
    public void setToPosition(TPosition value) {
        this.toPosition = value;
    }

    /**
     * Gets the value of the moveDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TMoveDetails }
     *     
     */
    public TMoveDetails getMoveDetails() {
        return moveDetails;
    }

    /**
     * Sets the value of the moveDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMoveDetails }
     *     
     */
    public void setMoveDetails(TMoveDetails value) {
        this.moveDetails = value;
    }

    /**
     * Gets the value of the moveKind property.
     * 
     * @return
     *     possible object is
     *     {@link TMoveKind }
     *     
     */
    public TMoveKind getMoveKind() {
        return moveKind;
    }

    /**
     * Sets the value of the moveKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMoveKind }
     *     
     */
    public void setMoveKind(TMoveKind value) {
        this.moveKind = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the isCorrectionOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCorrectionOnly() {
        return isCorrectionOnly;
    }

    /**
     * Sets the value of the isCorrectionOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCorrectionOnly(Boolean value) {
        this.isCorrectionOnly = value;
    }

}
