//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tMoveKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tMoveKind">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RECV"/>
 *     &lt;enumeration value="DLVR"/>
 *     &lt;enumeration value="DSCH"/>
 *     &lt;enumeration value="LOAD"/>
 *     &lt;enumeration value="RDSC"/>
 *     &lt;enumeration value="RLOD"/>
 *     &lt;enumeration value="SHOB"/>
 *     &lt;enumeration value="YARD"/>
 *     &lt;enumeration value="SHFT"/>
 *     &lt;enumeration value="OTHR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tMoveKind")
@XmlEnum
public enum TMoveKind {


    /**
     * Receival
     * 
     */
    RECV,

    /**
     * Delivery
     * 
     */
    DLVR,

    /**
     * Discharge
     * 
     */
    DSCH,

    /**
     * Load
     * 
     */
    LOAD,

    /**
     * Rail Disch
     * 
     */
    RDSC,

    /**
     * Rail Load
     * 
     */
    RLOD,

    /**
     * Shift O.B.
     * 
     */
    SHOB,

    /**
     * Yard Move
     * 
     */
    YARD,

    /**
     * Yard Shift
     * 
     */
    SHFT,

    /**
     * Other
     * 
     */
    OTHR;

    public String value() {
        return name();
    }

    public static TMoveKind fromValue(String v) {
        return valueOf(v);
    }

}
