//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Pool Member Equip Type
 * 
 * <p>Java class for tPoolEqTypes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPoolEqTypes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="equpment-type" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="iso-group" type="{http://www.navis.com/argo}tIsoGroup" />
 *                 &lt;attribute name="size" use="required" type="{http://www.navis.com/argo}tEquipNominalLength" />
 *                 &lt;attribute name="height" type="{http://www.navis.com/argo}tEquipNominalHeight" />
 *                 &lt;attribute name="joined" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="removed" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPoolEqTypes", propOrder = {
    "equpmentType"
})
public class TPoolEqTypes {

    @XmlElement(name = "equpment-type")
    protected List<TPoolEqTypes.EqupmentType> equpmentType;

    /**
     * Gets the value of the equpmentType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equpmentType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEqupmentType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TPoolEqTypes.EqupmentType }
     * 
     * 
     */
    public List<TPoolEqTypes.EqupmentType> getEqupmentType() {
        if (equpmentType == null) {
            equpmentType = new ArrayList<TPoolEqTypes.EqupmentType>();
        }
        return this.equpmentType;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="iso-group" type="{http://www.navis.com/argo}tIsoGroup" />
     *       &lt;attribute name="size" use="required" type="{http://www.navis.com/argo}tEquipNominalLength" />
     *       &lt;attribute name="height" type="{http://www.navis.com/argo}tEquipNominalHeight" />
     *       &lt;attribute name="joined" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="removed" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class EqupmentType {

        @XmlAttribute(name = "iso-group")
        protected TIsoGroup isoGroup;
        @XmlAttribute(required = true)
        protected TEquipNominalLength size;
        @XmlAttribute
        protected TEquipNominalHeight height;
        @XmlAttribute
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar joined;
        @XmlAttribute
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar removed;

        /**
         * Gets the value of the isoGroup property.
         * 
         * @return
         *     possible object is
         *     {@link TIsoGroup }
         *     
         */
        public TIsoGroup getIsoGroup() {
            return isoGroup;
        }

        /**
         * Sets the value of the isoGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link TIsoGroup }
         *     
         */
        public void setIsoGroup(TIsoGroup value) {
            this.isoGroup = value;
        }

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link TEquipNominalLength }
         *     
         */
        public TEquipNominalLength getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEquipNominalLength }
         *     
         */
        public void setSize(TEquipNominalLength value) {
            this.size = value;
        }

        /**
         * Gets the value of the height property.
         * 
         * @return
         *     possible object is
         *     {@link TEquipNominalHeight }
         *     
         */
        public TEquipNominalHeight getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEquipNominalHeight }
         *     
         */
        public void setHeight(TEquipNominalHeight value) {
            this.height = value;
        }

        /**
         * Gets the value of the joined property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getJoined() {
            return joined;
        }

        /**
         * Sets the value of the joined property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setJoined(XMLGregorianCalendar value) {
            this.joined = value;
        }

        /**
         * Gets the value of the removed property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getRemoved() {
            return removed;
        }

        /**
         * Sets the value of the removed property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setRemoved(XMLGregorianCalendar value) {
            this.removed = value;
        }

    }

}
