//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tPowerGuarantees complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPowerGuarantees">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="power-guarantee" type="{http://www.navis.com/argo}tGuarantee"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPowerGuarantees", propOrder = {
    "powerGuarantee"
})
public class TPowerGuarantees {

    @XmlElement(name = "power-guarantee", required = true)
    protected TGuarantee powerGuarantee;

    /**
     * Gets the value of the powerGuarantee property.
     * 
     * @return
     *     possible object is
     *     {@link TGuarantee }
     *     
     */
    public TGuarantee getPowerGuarantee() {
        return powerGuarantee;
    }

    /**
     * Sets the value of the powerGuarantee property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGuarantee }
     *     
     */
    public void setPowerGuarantee(TGuarantee value) {
        this.powerGuarantee = value;
    }

}
