//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Rarilcar Type
 * 
 * <p>Java class for tRailcarType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tRailcarType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="platforms" type="{http://www.navis.com/argo}tPlatforms" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="flat-car-type" type="{http://www.navis.com/argo}tRailcarFlatCarType" />
 *       &lt;attribute name="is-high-side" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="max-tiers-per-platform" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="max20s-per-platform" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="length-cm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="safe-weight-kg" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="height-cm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tare-weight-kg" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="life-cycle-state" type="{http://www.navis.com/argo}tLifeCycleStateType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tRailcarType", propOrder = {
    "platforms"
})
public class TRailcarType {

    protected TPlatforms platforms;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected String name;
    @XmlAttribute(name = "flat-car-type")
    protected TRailcarFlatCarType flatCarType;
    @XmlAttribute(name = "is-high-side")
    protected String isHighSide;
    @XmlAttribute(name = "max-tiers-per-platform")
    protected String maxTiersPerPlatform;
    @XmlAttribute(name = "max20s-per-platform")
    protected String max20SPerPlatform;
    @XmlAttribute(name = "length-cm")
    protected String lengthCm;
    @XmlAttribute(name = "safe-weight-kg")
    protected String safeWeightKg;
    @XmlAttribute(name = "height-cm")
    protected String heightCm;
    @XmlAttribute(name = "tare-weight-kg")
    protected String tareWeightKg;
    @XmlAttribute(name = "life-cycle-state")
    protected TLifeCycleStateType lifeCycleState;

    /**
     * Gets the value of the platforms property.
     * 
     * @return
     *     possible object is
     *     {@link TPlatforms }
     *     
     */
    public TPlatforms getPlatforms() {
        return platforms;
    }

    /**
     * Sets the value of the platforms property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPlatforms }
     *     
     */
    public void setPlatforms(TPlatforms value) {
        this.platforms = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the flatCarType property.
     * 
     * @return
     *     possible object is
     *     {@link TRailcarFlatCarType }
     *     
     */
    public TRailcarFlatCarType getFlatCarType() {
        return flatCarType;
    }

    /**
     * Sets the value of the flatCarType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRailcarFlatCarType }
     *     
     */
    public void setFlatCarType(TRailcarFlatCarType value) {
        this.flatCarType = value;
    }

    /**
     * Gets the value of the isHighSide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsHighSide() {
        return isHighSide;
    }

    /**
     * Sets the value of the isHighSide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsHighSide(String value) {
        this.isHighSide = value;
    }

    /**
     * Gets the value of the maxTiersPerPlatform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxTiersPerPlatform() {
        return maxTiersPerPlatform;
    }

    /**
     * Sets the value of the maxTiersPerPlatform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxTiersPerPlatform(String value) {
        this.maxTiersPerPlatform = value;
    }

    /**
     * Gets the value of the max20SPerPlatform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMax20SPerPlatform() {
        return max20SPerPlatform;
    }

    /**
     * Sets the value of the max20SPerPlatform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMax20SPerPlatform(String value) {
        this.max20SPerPlatform = value;
    }

    /**
     * Gets the value of the lengthCm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLengthCm() {
        return lengthCm;
    }

    /**
     * Sets the value of the lengthCm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLengthCm(String value) {
        this.lengthCm = value;
    }

    /**
     * Gets the value of the safeWeightKg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSafeWeightKg() {
        return safeWeightKg;
    }

    /**
     * Sets the value of the safeWeightKg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSafeWeightKg(String value) {
        this.safeWeightKg = value;
    }

    /**
     * Gets the value of the heightCm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeightCm() {
        return heightCm;
    }

    /**
     * Sets the value of the heightCm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeightCm(String value) {
        this.heightCm = value;
    }

    /**
     * Gets the value of the tareWeightKg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTareWeightKg() {
        return tareWeightKg;
    }

    /**
     * Sets the value of the tareWeightKg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTareWeightKg(String value) {
        this.tareWeightKg = value;
    }

    /**
     * Gets the value of the lifeCycleState property.
     * 
     * @return
     *     possible object is
     *     {@link TLifeCycleStateType }
     *     
     */
    public TLifeCycleStateType getLifeCycleState() {
        return lifeCycleState;
    }

    /**
     * Sets the value of the lifeCycleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLifeCycleStateType }
     *     
     */
    public void setLifeCycleState(TLifeCycleStateType value) {
        this.lifeCycleState = value;
    }

}
