//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tRailcarFlatCarType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tRailcarFlatCarType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TOFC"/>
 *     &lt;enumeration value="COFC"/>
 *     &lt;enumeration value="Convertible"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tRailcarFlatCarType")
@XmlEnum
public enum TRailcarFlatCarType {


    /**
     * Trailer on flat car
     * 
     */
    TOFC("TOFC"),

    /**
     * Container on flat car
     * 
     */
    COFC("COFC"),

    /**
     * Convertible
     * 
     */
    @XmlEnumValue("Convertible")
    CONVERTIBLE("Convertible");
    private final String value;

    TRailcarFlatCarType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TRailcarFlatCarType fromValue(String v) {
        for (TRailcarFlatCarType c: TRailcarFlatCarType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
