//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Defines an organization that acts as a Shipper
 * 
 * <p>Java class for tTruckingCompany complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTruckingCompany">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.navis.com/argo}tBusinessUnit">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="agent-representations" type="{http://www.navis.com/argo}tAgentRepresentations" minOccurs="0"/>
 *         &lt;element name="line-agreements" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="line-agreement" type="{http://www.navis.com/argo}tLineAgreement" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="update-mode" type="{http://www.navis.com/argo}tUpdateMode" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="drivers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="driver" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="license-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="card-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="update-mode" type="{http://www.navis.com/argo}tUpdateMode" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="groups" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="group" type="{http://www.navis.com/argo}tGroup" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="update-mode" type="{http://www.navis.com/argo}tUpdateMode" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="insurance-expires" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="is-eq-operator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="is-eq-owner" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="default-edo-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="line-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" type="{http://www.navis.com/argo}tTruckStatus" />
 *       &lt;attribute name="guarantee-limit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="is-exam-site-carrier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="is-seized-cargo-carrier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="exam-authorization-expires" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="seized-cargo-authorization-expires" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="life-cycle-state" type="{http://www.navis.com/argo}tLifeCycleStateType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTruckingCompany", propOrder = {
    "agentRepresentations",
    "lineAgreements",
    "drivers",
    "groups"
})
public class TTruckingCompany
    extends TBusinessUnit
{

    @XmlElement(name = "agent-representations")
    protected TAgentRepresentations agentRepresentations;
    @XmlElement(name = "line-agreements")
    protected TTruckingCompany.LineAgreements lineAgreements;
    protected TTruckingCompany.Drivers drivers;
    protected TTruckingCompany.Groups groups;
    @XmlAttribute(name = "insurance-expires")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar insuranceExpires;
    @XmlAttribute(name = "is-eq-operator")
    protected String isEqOperator;
    @XmlAttribute(name = "is-eq-owner")
    protected String isEqOwner;
    @XmlAttribute(name = "default-edo-nbr")
    protected String defaultEdoNbr;
    @XmlAttribute(name = "line-id")
    protected String lineId;
    @XmlAttribute
    protected TTruckStatus status;
    @XmlAttribute(name = "guarantee-limit")
    protected String guaranteeLimit;
    @XmlAttribute(name = "is-exam-site-carrier")
    protected String isExamSiteCarrier;
    @XmlAttribute(name = "is-seized-cargo-carrier")
    protected String isSeizedCargoCarrier;
    @XmlAttribute(name = "exam-authorization-expires")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar examAuthorizationExpires;
    @XmlAttribute(name = "seized-cargo-authorization-expires")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar seizedCargoAuthorizationExpires;
    @XmlAttribute(name = "life-cycle-state")
    protected TLifeCycleStateType lifeCycleState;

    /**
     * Gets the value of the agentRepresentations property.
     * 
     * @return
     *     possible object is
     *     {@link TAgentRepresentations }
     *     
     */
    public TAgentRepresentations getAgentRepresentations() {
        return agentRepresentations;
    }

    /**
     * Sets the value of the agentRepresentations property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAgentRepresentations }
     *     
     */
    public void setAgentRepresentations(TAgentRepresentations value) {
        this.agentRepresentations = value;
    }

    /**
     * Gets the value of the lineAgreements property.
     * 
     * @return
     *     possible object is
     *     {@link TTruckingCompany.LineAgreements }
     *     
     */
    public TTruckingCompany.LineAgreements getLineAgreements() {
        return lineAgreements;
    }

    /**
     * Sets the value of the lineAgreements property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTruckingCompany.LineAgreements }
     *     
     */
    public void setLineAgreements(TTruckingCompany.LineAgreements value) {
        this.lineAgreements = value;
    }

    /**
     * Gets the value of the drivers property.
     * 
     * @return
     *     possible object is
     *     {@link TTruckingCompany.Drivers }
     *     
     */
    public TTruckingCompany.Drivers getDrivers() {
        return drivers;
    }

    /**
     * Sets the value of the drivers property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTruckingCompany.Drivers }
     *     
     */
    public void setDrivers(TTruckingCompany.Drivers value) {
        this.drivers = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link TTruckingCompany.Groups }
     *     
     */
    public TTruckingCompany.Groups getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTruckingCompany.Groups }
     *     
     */
    public void setGroups(TTruckingCompany.Groups value) {
        this.groups = value;
    }

    /**
     * Gets the value of the insuranceExpires property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInsuranceExpires() {
        return insuranceExpires;
    }

    /**
     * Sets the value of the insuranceExpires property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInsuranceExpires(XMLGregorianCalendar value) {
        this.insuranceExpires = value;
    }

    /**
     * Gets the value of the isEqOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEqOperator() {
        return isEqOperator;
    }

    /**
     * Sets the value of the isEqOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEqOperator(String value) {
        this.isEqOperator = value;
    }

    /**
     * Gets the value of the isEqOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEqOwner() {
        return isEqOwner;
    }

    /**
     * Sets the value of the isEqOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEqOwner(String value) {
        this.isEqOwner = value;
    }

    /**
     * Gets the value of the defaultEdoNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultEdoNbr() {
        return defaultEdoNbr;
    }

    /**
     * Sets the value of the defaultEdoNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultEdoNbr(String value) {
        this.defaultEdoNbr = value;
    }

    /**
     * Gets the value of the lineId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * Sets the value of the lineId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineId(String value) {
        this.lineId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link TTruckStatus }
     *     
     */
    public TTruckStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTruckStatus }
     *     
     */
    public void setStatus(TTruckStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the guaranteeLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuaranteeLimit() {
        return guaranteeLimit;
    }

    /**
     * Sets the value of the guaranteeLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuaranteeLimit(String value) {
        this.guaranteeLimit = value;
    }

    /**
     * Gets the value of the isExamSiteCarrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsExamSiteCarrier() {
        return isExamSiteCarrier;
    }

    /**
     * Sets the value of the isExamSiteCarrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsExamSiteCarrier(String value) {
        this.isExamSiteCarrier = value;
    }

    /**
     * Gets the value of the isSeizedCargoCarrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsSeizedCargoCarrier() {
        return isSeizedCargoCarrier;
    }

    /**
     * Sets the value of the isSeizedCargoCarrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSeizedCargoCarrier(String value) {
        this.isSeizedCargoCarrier = value;
    }

    /**
     * Gets the value of the examAuthorizationExpires property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExamAuthorizationExpires() {
        return examAuthorizationExpires;
    }

    /**
     * Sets the value of the examAuthorizationExpires property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExamAuthorizationExpires(XMLGregorianCalendar value) {
        this.examAuthorizationExpires = value;
    }

    /**
     * Gets the value of the seizedCargoAuthorizationExpires property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSeizedCargoAuthorizationExpires() {
        return seizedCargoAuthorizationExpires;
    }

    /**
     * Sets the value of the seizedCargoAuthorizationExpires property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSeizedCargoAuthorizationExpires(XMLGregorianCalendar value) {
        this.seizedCargoAuthorizationExpires = value;
    }

    /**
     * Gets the value of the lifeCycleState property.
     * 
     * @return
     *     possible object is
     *     {@link TLifeCycleStateType }
     *     
     */
    public TLifeCycleStateType getLifeCycleState() {
        return lifeCycleState;
    }

    /**
     * Sets the value of the lifeCycleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLifeCycleStateType }
     *     
     */
    public void setLifeCycleState(TLifeCycleStateType value) {
        this.lifeCycleState = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="driver" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="license-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="card-id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="update-mode" type="{http://www.navis.com/argo}tUpdateMode" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "driver"
    })
    public static class Drivers {

        protected List<TTruckingCompany.Drivers.Driver> driver;
        @XmlAttribute(name = "update-mode")
        protected TUpdateMode updateMode;

        /**
         * Gets the value of the driver property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the driver property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDriver().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TTruckingCompany.Drivers.Driver }
         * 
         * 
         */
        public List<TTruckingCompany.Drivers.Driver> getDriver() {
            if (driver == null) {
                driver = new ArrayList<TTruckingCompany.Drivers.Driver>();
            }
            return this.driver;
        }

        /**
         * Gets the value of the updateMode property.
         * 
         * @return
         *     possible object is
         *     {@link TUpdateMode }
         *     
         */
        public TUpdateMode getUpdateMode() {
            return updateMode;
        }

        /**
         * Sets the value of the updateMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUpdateMode }
         *     
         */
        public void setUpdateMode(TUpdateMode value) {
            this.updateMode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="license-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="card-id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Driver {

            @XmlAttribute
            protected String name;
            @XmlAttribute(name = "license-nbr")
            protected String licenseNbr;
            @XmlAttribute(name = "card-id")
            protected String cardId;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the licenseNbr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLicenseNbr() {
                return licenseNbr;
            }

            /**
             * Sets the value of the licenseNbr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLicenseNbr(String value) {
                this.licenseNbr = value;
            }

            /**
             * Gets the value of the cardId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCardId() {
                return cardId;
            }

            /**
             * Sets the value of the cardId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCardId(String value) {
                this.cardId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="group" type="{http://www.navis.com/argo}tGroup" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="update-mode" type="{http://www.navis.com/argo}tUpdateMode" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "group"
    })
    public static class Groups {

        protected List<TGroup> group;
        @XmlAttribute(name = "update-mode")
        protected TUpdateMode updateMode;

        /**
         * Gets the value of the group property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the group property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TGroup }
         * 
         * 
         */
        public List<TGroup> getGroup() {
            if (group == null) {
                group = new ArrayList<TGroup>();
            }
            return this.group;
        }

        /**
         * Gets the value of the updateMode property.
         * 
         * @return
         *     possible object is
         *     {@link TUpdateMode }
         *     
         */
        public TUpdateMode getUpdateMode() {
            return updateMode;
        }

        /**
         * Sets the value of the updateMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUpdateMode }
         *     
         */
        public void setUpdateMode(TUpdateMode value) {
            this.updateMode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="line-agreement" type="{http://www.navis.com/argo}tLineAgreement" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="update-mode" type="{http://www.navis.com/argo}tUpdateMode" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lineAgreement"
    })
    public static class LineAgreements {

        @XmlElement(name = "line-agreement")
        protected List<TLineAgreement> lineAgreement;
        @XmlAttribute(name = "update-mode")
        protected TUpdateMode updateMode;

        /**
         * Gets the value of the lineAgreement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the lineAgreement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLineAgreement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TLineAgreement }
         * 
         * 
         */
        public List<TLineAgreement> getLineAgreement() {
            if (lineAgreement == null) {
                lineAgreement = new ArrayList<TLineAgreement>();
            }
            return this.lineAgreement;
        }

        /**
         * Gets the value of the updateMode property.
         * 
         * @return
         *     possible object is
         *     {@link TUpdateMode }
         *     
         */
        public TUpdateMode getUpdateMode() {
            return updateMode;
        }

        /**
         * Sets the value of the updateMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link TUpdateMode }
         *     
         */
        public void setUpdateMode(TUpdateMode value) {
            this.updateMode = value;
        }

    }

}
