//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tUnitContents complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tUnitContents">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="freight-kind" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="weight-kg" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="weight-kg-advised" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="weight-kg-gate-measured" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="weight-kg-yard-measured" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="bl-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="commodity-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="commodity-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="consignee-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="consignee-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="shipper-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="shipper-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tUnitContents")
public class TUnitContents {

    @XmlAttribute(name = "freight-kind")
    @XmlSchemaType(name = "anySimpleType")
    protected String freightKind;
    @XmlAttribute(name = "weight-kg")
    protected BigDecimal weightKg;
    @XmlAttribute(name = "weight-kg-advised")
    protected BigDecimal weightKgAdvised;
    @XmlAttribute(name = "weight-kg-gate-measured")
    protected BigDecimal weightKgGateMeasured;
    @XmlAttribute(name = "weight-kg-yard-measured")
    protected BigDecimal weightKgYardMeasured;
    @XmlAttribute(name = "bl-nbr")
    protected String blNbr;
    @XmlAttribute(name = "commodity-id")
    protected String commodityId;
    @XmlAttribute(name = "commodity-name")
    protected String commodityName;
    @XmlAttribute(name = "consignee-id")
    protected String consigneeId;
    @XmlAttribute(name = "consignee-name")
    protected String consigneeName;
    @XmlAttribute(name = "shipper-id")
    protected String shipperId;
    @XmlAttribute(name = "shipper-name")
    protected String shipperName;

    /**
     * Gets the value of the freightKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreightKind() {
        return freightKind;
    }

    /**
     * Sets the value of the freightKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreightKind(String value) {
        this.freightKind = value;
    }

    /**
     * Gets the value of the weightKg property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeightKg() {
        return weightKg;
    }

    /**
     * Sets the value of the weightKg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeightKg(BigDecimal value) {
        this.weightKg = value;
    }

    /**
     * Gets the value of the weightKgAdvised property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeightKgAdvised() {
        return weightKgAdvised;
    }

    /**
     * Sets the value of the weightKgAdvised property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeightKgAdvised(BigDecimal value) {
        this.weightKgAdvised = value;
    }

    /**
     * Gets the value of the weightKgGateMeasured property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeightKgGateMeasured() {
        return weightKgGateMeasured;
    }

    /**
     * Sets the value of the weightKgGateMeasured property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeightKgGateMeasured(BigDecimal value) {
        this.weightKgGateMeasured = value;
    }

    /**
     * Gets the value of the weightKgYardMeasured property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeightKgYardMeasured() {
        return weightKgYardMeasured;
    }

    /**
     * Sets the value of the weightKgYardMeasured property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeightKgYardMeasured(BigDecimal value) {
        this.weightKgYardMeasured = value;
    }

    /**
     * Gets the value of the blNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlNbr() {
        return blNbr;
    }

    /**
     * Sets the value of the blNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlNbr(String value) {
        this.blNbr = value;
    }

    /**
     * Gets the value of the commodityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * Sets the value of the commodityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityId(String value) {
        this.commodityId = value;
    }

    /**
     * Gets the value of the commodityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * Sets the value of the commodityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityName(String value) {
        this.commodityName = value;
    }

    /**
     * Gets the value of the consigneeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsigneeId() {
        return consigneeId;
    }

    /**
     * Sets the value of the consigneeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsigneeId(String value) {
        this.consigneeId = value;
    }

    /**
     * Gets the value of the consigneeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsigneeName() {
        return consigneeName;
    }

    /**
     * Sets the value of the consigneeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsigneeName(String value) {
        this.consigneeName = value;
    }

    /**
     * Gets the value of the shipperId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipperId() {
        return shipperId;
    }

    /**
     * Sets the value of the shipperId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipperId(String value) {
        this.shipperId = value;
    }

    /**
     * Gets the value of the shipperName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipperName() {
        return shipperName;
    }

    /**
     * Sets the value of the shipperName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipperName(String value) {
        this.shipperName = value;
    }

}
