//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 01:33:48 PM GMT-10:00 
//


package com.matson.tos.jaxb.snx;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A vesselVisit is the contiguous block of time spent at the facility by
 *                 a vessel from arrival to departure
 *             
 * 
 * <p>Java class for tVesselVisit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tVesselVisit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lines" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="line" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                           &lt;attribute name="in-voy-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="out-voy-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="time-cargo-cutoff" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="time-empty-pickup" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="berths" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="berthing" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="quay-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ship-side-to">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *                                 &lt;enumeration value="UNKNOWN"/>
 *                                 &lt;enumeration value="STARBOARD"/>
 *                                 &lt;enumeration value="PORTSIDE"/>
 *                                 &lt;enumeration value="STERNSIDETO"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="time-shift" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="est-move-count" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="bbk-discharge" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="bbk-load" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="discharge" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="load" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="restow" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="shift" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ATA" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="ATD" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="ETA" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="ETD" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="in-voy-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="in-call-number" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="inbound-first-free-day" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="is-common-carrier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="is-dray-off" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="is-no-client-access" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="notes" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="out-voy-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operator-id" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="out-call-number" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="published-eta" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="published-etd" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="service-id" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="itinerary-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="time-begin-receive" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="time-cargo-cutoff" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="time-discharge-complete" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="time-end-work" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="time-first-availability" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="time-haz-cutoff" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="time-labor-off-board" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="time-labor-on-board" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="time-pilot-off-board" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="time-pilot-on-board" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="time-reefer-cutoff" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="time-start-work" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="vessel-id" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="vessel-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="visit-phase">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *             &lt;enumeration value="CREATED"/>
 *             &lt;enumeration value="INBOUND"/>
 *             &lt;enumeration value="ARRIVED"/>
 *             &lt;enumeration value="WORKING"/>
 *             &lt;enumeration value="COMPLETE"/>
 *             &lt;enumeration value="DEPARTED"/>
 *             &lt;enumeration value="CLOSED"/>
 *             &lt;enumeration value="CANCELED"/>
 *             &lt;enumeration value="ARCHIVED"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="validate-phase" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="facility" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="next-facility" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="classification">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *             &lt;enumeration value="DEEPSEA"/>
 *             &lt;enumeration value="BARGE"/>
 *             &lt;enumeration value="FEEDER"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="vv-flex-string-1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vv-flex-string-2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vv-flex-string-3" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vv-flex-string-4" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vv-flex-string-5" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vv-flex-string-6" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vv-flex-string-7" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vv-flex-string-8" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vv-flex-date-1" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="vv-flex-date-2" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="vv-flex-date-3" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="vv-flex-date-4" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="vv-flex-date-5" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="vv-flex-date-6" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="vv-flex-date-7" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="vv-flex-date-8" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tVesselVisit", propOrder = {
    "lines",
    "berths",
    "estMoveCount"
})
public class TVesselVisit {

    protected TVesselVisit.Lines lines;
    protected TVesselVisit.Berths berths;
    @XmlElement(name = "est-move-count")
    protected TVesselVisit.EstMoveCount estMoveCount;
    @XmlAttribute(name = "ATA")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ata;
    @XmlAttribute(name = "ATD")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar atd;
    @XmlAttribute(name = "ETA")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eta;
    @XmlAttribute(name = "ETD")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar etd;
    @XmlAttribute(name = "in-voy-nbr")
    protected String inVoyNbr;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String id;
    @XmlAttribute(name = "in-call-number")
    protected BigInteger inCallNumber;
    @XmlAttribute(name = "inbound-first-free-day")
    @XmlSchemaType(name = "anySimpleType")
    protected String inboundFirstFreeDay;
    @XmlAttribute(name = "is-common-carrier")
    protected String isCommonCarrier;
    @XmlAttribute(name = "is-dray-off")
    protected String isDrayOff;
    @XmlAttribute(name = "is-no-client-access")
    protected String isNoClientAccess;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String notes;
    @XmlAttribute(name = "out-voy-nbr")
    protected String outVoyNbr;
    @XmlAttribute(name = "operator-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String operatorId;
    @XmlAttribute(name = "out-call-number")
    protected BigInteger outCallNumber;
    @XmlAttribute(name = "published-eta")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar publishedEta;
    @XmlAttribute(name = "published-etd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar publishedEtd;
    @XmlAttribute(name = "service-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String serviceId;
    @XmlAttribute(name = "itinerary-id")
    protected String itineraryId;
    @XmlAttribute(name = "time-begin-receive")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeBeginReceive;
    @XmlAttribute(name = "time-cargo-cutoff")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeCargoCutoff;
    @XmlAttribute(name = "time-discharge-complete")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeDischargeComplete;
    @XmlAttribute(name = "time-end-work")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeEndWork;
    @XmlAttribute(name = "time-first-availability")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeFirstAvailability;
    @XmlAttribute(name = "time-haz-cutoff")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeHazCutoff;
    @XmlAttribute(name = "time-labor-off-board")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeLaborOffBoard;
    @XmlAttribute(name = "time-labor-on-board")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeLaborOnBoard;
    @XmlAttribute(name = "time-pilot-off-board")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timePilotOffBoard;
    @XmlAttribute(name = "time-pilot-on-board")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timePilotOnBoard;
    @XmlAttribute(name = "time-reefer-cutoff")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeReeferCutoff;
    @XmlAttribute(name = "time-start-work")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStartWork;
    @XmlAttribute(name = "vessel-id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String vesselId;
    @XmlAttribute(name = "vessel-name")
    protected String vesselName;
    @XmlAttribute(name = "visit-phase")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String visitPhase;
    @XmlAttribute(name = "validate-phase")
    @XmlSchemaType(name = "anySimpleType")
    protected String validatePhase;
    @XmlAttribute
    protected String facility;
    @XmlAttribute(name = "next-facility")
    protected String nextFacility;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String classification;
    @XmlAttribute(name = "vv-flex-string-1")
    protected String vvFlexString1;
    @XmlAttribute(name = "vv-flex-string-2")
    protected String vvFlexString2;
    @XmlAttribute(name = "vv-flex-string-3")
    protected String vvFlexString3;
    @XmlAttribute(name = "vv-flex-string-4")
    protected String vvFlexString4;
    @XmlAttribute(name = "vv-flex-string-5")
    protected String vvFlexString5;
    @XmlAttribute(name = "vv-flex-string-6")
    protected String vvFlexString6;
    @XmlAttribute(name = "vv-flex-string-7")
    protected String vvFlexString7;
    @XmlAttribute(name = "vv-flex-string-8")
    protected String vvFlexString8;
    @XmlAttribute(name = "vv-flex-date-1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vvFlexDate1;
    @XmlAttribute(name = "vv-flex-date-2")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vvFlexDate2;
    @XmlAttribute(name = "vv-flex-date-3")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vvFlexDate3;
    @XmlAttribute(name = "vv-flex-date-4")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vvFlexDate4;
    @XmlAttribute(name = "vv-flex-date-5")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vvFlexDate5;
    @XmlAttribute(name = "vv-flex-date-6")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vvFlexDate6;
    @XmlAttribute(name = "vv-flex-date-7")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vvFlexDate7;
    @XmlAttribute(name = "vv-flex-date-8")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vvFlexDate8;

    /**
     * Gets the value of the lines property.
     * 
     * @return
     *     possible object is
     *     {@link TVesselVisit.Lines }
     *     
     */
    public TVesselVisit.Lines getLines() {
        return lines;
    }

    /**
     * Sets the value of the lines property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVesselVisit.Lines }
     *     
     */
    public void setLines(TVesselVisit.Lines value) {
        this.lines = value;
    }

    /**
     * Gets the value of the berths property.
     * 
     * @return
     *     possible object is
     *     {@link TVesselVisit.Berths }
     *     
     */
    public TVesselVisit.Berths getBerths() {
        return berths;
    }

    /**
     * Sets the value of the berths property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVesselVisit.Berths }
     *     
     */
    public void setBerths(TVesselVisit.Berths value) {
        this.berths = value;
    }

    /**
     * Gets the value of the estMoveCount property.
     * 
     * @return
     *     possible object is
     *     {@link TVesselVisit.EstMoveCount }
     *     
     */
    public TVesselVisit.EstMoveCount getEstMoveCount() {
        return estMoveCount;
    }

    /**
     * Sets the value of the estMoveCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVesselVisit.EstMoveCount }
     *     
     */
    public void setEstMoveCount(TVesselVisit.EstMoveCount value) {
        this.estMoveCount = value;
    }

    /**
     * Gets the value of the ata property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getATA() {
        return ata;
    }

    /**
     * Sets the value of the ata property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setATA(XMLGregorianCalendar value) {
        this.ata = value;
    }

    /**
     * Gets the value of the atd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getATD() {
        return atd;
    }

    /**
     * Sets the value of the atd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setATD(XMLGregorianCalendar value) {
        this.atd = value;
    }

    /**
     * Gets the value of the eta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getETA() {
        return eta;
    }

    /**
     * Sets the value of the eta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setETA(XMLGregorianCalendar value) {
        this.eta = value;
    }

    /**
     * Gets the value of the etd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getETD() {
        return etd;
    }

    /**
     * Sets the value of the etd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setETD(XMLGregorianCalendar value) {
        this.etd = value;
    }

    /**
     * Gets the value of the inVoyNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInVoyNbr() {
        return inVoyNbr;
    }

    /**
     * Sets the value of the inVoyNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInVoyNbr(String value) {
        this.inVoyNbr = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the inCallNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInCallNumber() {
        return inCallNumber;
    }

    /**
     * Sets the value of the inCallNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInCallNumber(BigInteger value) {
        this.inCallNumber = value;
    }

    /**
     * Gets the value of the inboundFirstFreeDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInboundFirstFreeDay() {
        return inboundFirstFreeDay;
    }

    /**
     * Sets the value of the inboundFirstFreeDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInboundFirstFreeDay(String value) {
        this.inboundFirstFreeDay = value;
    }

    /**
     * Gets the value of the isCommonCarrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsCommonCarrier() {
        return isCommonCarrier;
    }

    /**
     * Sets the value of the isCommonCarrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsCommonCarrier(String value) {
        this.isCommonCarrier = value;
    }

    /**
     * Gets the value of the isDrayOff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDrayOff() {
        return isDrayOff;
    }

    /**
     * Sets the value of the isDrayOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDrayOff(String value) {
        this.isDrayOff = value;
    }

    /**
     * Gets the value of the isNoClientAccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsNoClientAccess() {
        return isNoClientAccess;
    }

    /**
     * Sets the value of the isNoClientAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsNoClientAccess(String value) {
        this.isNoClientAccess = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the outVoyNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutVoyNbr() {
        return outVoyNbr;
    }

    /**
     * Sets the value of the outVoyNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutVoyNbr(String value) {
        this.outVoyNbr = value;
    }

    /**
     * Gets the value of the operatorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * Sets the value of the operatorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorId(String value) {
        this.operatorId = value;
    }

    /**
     * Gets the value of the outCallNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOutCallNumber() {
        return outCallNumber;
    }

    /**
     * Sets the value of the outCallNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOutCallNumber(BigInteger value) {
        this.outCallNumber = value;
    }

    /**
     * Gets the value of the publishedEta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublishedEta() {
        return publishedEta;
    }

    /**
     * Sets the value of the publishedEta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublishedEta(XMLGregorianCalendar value) {
        this.publishedEta = value;
    }

    /**
     * Gets the value of the publishedEtd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublishedEtd() {
        return publishedEtd;
    }

    /**
     * Sets the value of the publishedEtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublishedEtd(XMLGregorianCalendar value) {
        this.publishedEtd = value;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceId(String value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the itineraryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItineraryId() {
        return itineraryId;
    }

    /**
     * Sets the value of the itineraryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItineraryId(String value) {
        this.itineraryId = value;
    }

    /**
     * Gets the value of the timeBeginReceive property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeBeginReceive() {
        return timeBeginReceive;
    }

    /**
     * Sets the value of the timeBeginReceive property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeBeginReceive(XMLGregorianCalendar value) {
        this.timeBeginReceive = value;
    }

    /**
     * Gets the value of the timeCargoCutoff property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeCargoCutoff() {
        return timeCargoCutoff;
    }

    /**
     * Sets the value of the timeCargoCutoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeCargoCutoff(XMLGregorianCalendar value) {
        this.timeCargoCutoff = value;
    }

    /**
     * Gets the value of the timeDischargeComplete property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeDischargeComplete() {
        return timeDischargeComplete;
    }

    /**
     * Sets the value of the timeDischargeComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeDischargeComplete(XMLGregorianCalendar value) {
        this.timeDischargeComplete = value;
    }

    /**
     * Gets the value of the timeEndWork property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeEndWork() {
        return timeEndWork;
    }

    /**
     * Sets the value of the timeEndWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeEndWork(XMLGregorianCalendar value) {
        this.timeEndWork = value;
    }

    /**
     * Gets the value of the timeFirstAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeFirstAvailability() {
        return timeFirstAvailability;
    }

    /**
     * Sets the value of the timeFirstAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeFirstAvailability(XMLGregorianCalendar value) {
        this.timeFirstAvailability = value;
    }

    /**
     * Gets the value of the timeHazCutoff property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeHazCutoff() {
        return timeHazCutoff;
    }

    /**
     * Sets the value of the timeHazCutoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeHazCutoff(XMLGregorianCalendar value) {
        this.timeHazCutoff = value;
    }

    /**
     * Gets the value of the timeLaborOffBoard property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeLaborOffBoard() {
        return timeLaborOffBoard;
    }

    /**
     * Sets the value of the timeLaborOffBoard property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeLaborOffBoard(XMLGregorianCalendar value) {
        this.timeLaborOffBoard = value;
    }

    /**
     * Gets the value of the timeLaborOnBoard property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeLaborOnBoard() {
        return timeLaborOnBoard;
    }

    /**
     * Sets the value of the timeLaborOnBoard property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeLaborOnBoard(XMLGregorianCalendar value) {
        this.timeLaborOnBoard = value;
    }

    /**
     * Gets the value of the timePilotOffBoard property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimePilotOffBoard() {
        return timePilotOffBoard;
    }

    /**
     * Sets the value of the timePilotOffBoard property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimePilotOffBoard(XMLGregorianCalendar value) {
        this.timePilotOffBoard = value;
    }

    /**
     * Gets the value of the timePilotOnBoard property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimePilotOnBoard() {
        return timePilotOnBoard;
    }

    /**
     * Sets the value of the timePilotOnBoard property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimePilotOnBoard(XMLGregorianCalendar value) {
        this.timePilotOnBoard = value;
    }

    /**
     * Gets the value of the timeReeferCutoff property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeReeferCutoff() {
        return timeReeferCutoff;
    }

    /**
     * Sets the value of the timeReeferCutoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeReeferCutoff(XMLGregorianCalendar value) {
        this.timeReeferCutoff = value;
    }

    /**
     * Gets the value of the timeStartWork property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStartWork() {
        return timeStartWork;
    }

    /**
     * Sets the value of the timeStartWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStartWork(XMLGregorianCalendar value) {
        this.timeStartWork = value;
    }

    /**
     * Gets the value of the vesselId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselId() {
        return vesselId;
    }

    /**
     * Sets the value of the vesselId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselId(String value) {
        this.vesselId = value;
    }

    /**
     * Gets the value of the vesselName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselName() {
        return vesselName;
    }

    /**
     * Sets the value of the vesselName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselName(String value) {
        this.vesselName = value;
    }

    /**
     * Gets the value of the visitPhase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitPhase() {
        return visitPhase;
    }

    /**
     * Sets the value of the visitPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitPhase(String value) {
        this.visitPhase = value;
    }

    /**
     * Gets the value of the validatePhase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidatePhase() {
        return validatePhase;
    }

    /**
     * Sets the value of the validatePhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidatePhase(String value) {
        this.validatePhase = value;
    }

    /**
     * Gets the value of the facility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacility() {
        return facility;
    }

    /**
     * Sets the value of the facility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacility(String value) {
        this.facility = value;
    }

    /**
     * Gets the value of the nextFacility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextFacility() {
        return nextFacility;
    }

    /**
     * Sets the value of the nextFacility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextFacility(String value) {
        this.nextFacility = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassification(String value) {
        this.classification = value;
    }

    /**
     * Gets the value of the vvFlexString1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVvFlexString1() {
        return vvFlexString1;
    }

    /**
     * Sets the value of the vvFlexString1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVvFlexString1(String value) {
        this.vvFlexString1 = value;
    }

    /**
     * Gets the value of the vvFlexString2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVvFlexString2() {
        return vvFlexString2;
    }

    /**
     * Sets the value of the vvFlexString2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVvFlexString2(String value) {
        this.vvFlexString2 = value;
    }

    /**
     * Gets the value of the vvFlexString3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVvFlexString3() {
        return vvFlexString3;
    }

    /**
     * Sets the value of the vvFlexString3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVvFlexString3(String value) {
        this.vvFlexString3 = value;
    }

    /**
     * Gets the value of the vvFlexString4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVvFlexString4() {
        return vvFlexString4;
    }

    /**
     * Sets the value of the vvFlexString4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVvFlexString4(String value) {
        this.vvFlexString4 = value;
    }

    /**
     * Gets the value of the vvFlexString5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVvFlexString5() {
        return vvFlexString5;
    }

    /**
     * Sets the value of the vvFlexString5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVvFlexString5(String value) {
        this.vvFlexString5 = value;
    }

    /**
     * Gets the value of the vvFlexString6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVvFlexString6() {
        return vvFlexString6;
    }

    /**
     * Sets the value of the vvFlexString6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVvFlexString6(String value) {
        this.vvFlexString6 = value;
    }

    /**
     * Gets the value of the vvFlexString7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVvFlexString7() {
        return vvFlexString7;
    }

    /**
     * Sets the value of the vvFlexString7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVvFlexString7(String value) {
        this.vvFlexString7 = value;
    }

    /**
     * Gets the value of the vvFlexString8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVvFlexString8() {
        return vvFlexString8;
    }

    /**
     * Sets the value of the vvFlexString8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVvFlexString8(String value) {
        this.vvFlexString8 = value;
    }

    /**
     * Gets the value of the vvFlexDate1 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVvFlexDate1() {
        return vvFlexDate1;
    }

    /**
     * Sets the value of the vvFlexDate1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVvFlexDate1(XMLGregorianCalendar value) {
        this.vvFlexDate1 = value;
    }

    /**
     * Gets the value of the vvFlexDate2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVvFlexDate2() {
        return vvFlexDate2;
    }

    /**
     * Sets the value of the vvFlexDate2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVvFlexDate2(XMLGregorianCalendar value) {
        this.vvFlexDate2 = value;
    }

    /**
     * Gets the value of the vvFlexDate3 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVvFlexDate3() {
        return vvFlexDate3;
    }

    /**
     * Sets the value of the vvFlexDate3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVvFlexDate3(XMLGregorianCalendar value) {
        this.vvFlexDate3 = value;
    }

    /**
     * Gets the value of the vvFlexDate4 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVvFlexDate4() {
        return vvFlexDate4;
    }

    /**
     * Sets the value of the vvFlexDate4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVvFlexDate4(XMLGregorianCalendar value) {
        this.vvFlexDate4 = value;
    }

    /**
     * Gets the value of the vvFlexDate5 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVvFlexDate5() {
        return vvFlexDate5;
    }

    /**
     * Sets the value of the vvFlexDate5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVvFlexDate5(XMLGregorianCalendar value) {
        this.vvFlexDate5 = value;
    }

    /**
     * Gets the value of the vvFlexDate6 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVvFlexDate6() {
        return vvFlexDate6;
    }

    /**
     * Sets the value of the vvFlexDate6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVvFlexDate6(XMLGregorianCalendar value) {
        this.vvFlexDate6 = value;
    }

    /**
     * Gets the value of the vvFlexDate7 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVvFlexDate7() {
        return vvFlexDate7;
    }

    /**
     * Sets the value of the vvFlexDate7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVvFlexDate7(XMLGregorianCalendar value) {
        this.vvFlexDate7 = value;
    }

    /**
     * Gets the value of the vvFlexDate8 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVvFlexDate8() {
        return vvFlexDate8;
    }

    /**
     * Sets the value of the vvFlexDate8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVvFlexDate8(XMLGregorianCalendar value) {
        this.vvFlexDate8 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="berthing" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="quay-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ship-side-to">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
     *                       &lt;enumeration value="UNKNOWN"/>
     *                       &lt;enumeration value="STARBOARD"/>
     *                       &lt;enumeration value="PORTSIDE"/>
     *                       &lt;enumeration value="STERNSIDETO"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="time-shift" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "berthing"
    })
    public static class Berths {

        protected List<TVesselVisit.Berths.Berthing> berthing;

        /**
         * Gets the value of the berthing property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the berthing property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBerthing().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TVesselVisit.Berths.Berthing }
         * 
         * 
         */
        public List<TVesselVisit.Berths.Berthing> getBerthing() {
            if (berthing == null) {
                berthing = new ArrayList<TVesselVisit.Berths.Berthing>();
            }
            return this.berthing;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="quay-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ship-side-to">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
         *             &lt;enumeration value="UNKNOWN"/>
         *             &lt;enumeration value="STARBOARD"/>
         *             &lt;enumeration value="PORTSIDE"/>
         *             &lt;enumeration value="STERNSIDETO"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="time-shift" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Berthing {

            @XmlAttribute(name = "quay-id", required = true)
            protected String quayId;
            @XmlAttribute(name = "ship-side-to")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String shipSideTo;
            @XmlAttribute(name = "time-shift")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar timeShift;

            /**
             * Gets the value of the quayId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuayId() {
                return quayId;
            }

            /**
             * Sets the value of the quayId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuayId(String value) {
                this.quayId = value;
            }

            /**
             * Gets the value of the shipSideTo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShipSideTo() {
                return shipSideTo;
            }

            /**
             * Sets the value of the shipSideTo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShipSideTo(String value) {
                this.shipSideTo = value;
            }

            /**
             * Gets the value of the timeShift property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTimeShift() {
                return timeShift;
            }

            /**
             * Sets the value of the timeShift property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTimeShift(XMLGregorianCalendar value) {
                this.timeShift = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="bbk-discharge" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="bbk-load" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="discharge" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="load" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="restow" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="shift" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class EstMoveCount {

        @XmlAttribute(name = "bbk-discharge")
        protected BigInteger bbkDischarge;
        @XmlAttribute(name = "bbk-load")
        protected BigInteger bbkLoad;
        @XmlAttribute
        protected BigInteger discharge;
        @XmlAttribute
        protected BigInteger load;
        @XmlAttribute
        protected BigInteger restow;
        @XmlAttribute
        protected BigInteger shift;

        /**
         * Gets the value of the bbkDischarge property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBbkDischarge() {
            return bbkDischarge;
        }

        /**
         * Sets the value of the bbkDischarge property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBbkDischarge(BigInteger value) {
            this.bbkDischarge = value;
        }

        /**
         * Gets the value of the bbkLoad property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBbkLoad() {
            return bbkLoad;
        }

        /**
         * Sets the value of the bbkLoad property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBbkLoad(BigInteger value) {
            this.bbkLoad = value;
        }

        /**
         * Gets the value of the discharge property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDischarge() {
            return discharge;
        }

        /**
         * Sets the value of the discharge property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDischarge(BigInteger value) {
            this.discharge = value;
        }

        /**
         * Gets the value of the load property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLoad() {
            return load;
        }

        /**
         * Sets the value of the load property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLoad(BigInteger value) {
            this.load = value;
        }

        /**
         * Gets the value of the restow property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getRestow() {
            return restow;
        }

        /**
         * Sets the value of the restow property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRestow(BigInteger value) {
            this.restow = value;
        }

        /**
         * Gets the value of the shift property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getShift() {
            return shift;
        }

        /**
         * Sets the value of the shift property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setShift(BigInteger value) {
            this.shift = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="line" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *                 &lt;attribute name="in-voy-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="out-voy-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="time-cargo-cutoff" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                 &lt;attribute name="time-empty-pickup" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "line"
    })
    public static class Lines {

        protected List<TVesselVisit.Lines.Line> line;

        /**
         * Gets the value of the line property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the line property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TVesselVisit.Lines.Line }
         * 
         * 
         */
        public List<TVesselVisit.Lines.Line> getLine() {
            if (line == null) {
                line = new ArrayList<TVesselVisit.Lines.Line>();
            }
            return this.line;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
         *       &lt;attribute name="in-voy-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="out-voy-nbr" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="time-cargo-cutoff" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *       &lt;attribute name="time-empty-pickup" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Line {

            @XmlAttribute(required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NCName")
            protected String id;
            @XmlAttribute(name = "in-voy-nbr")
            protected String inVoyNbr;
            @XmlAttribute(name = "out-voy-nbr")
            protected String outVoyNbr;
            @XmlAttribute(name = "time-cargo-cutoff")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar timeCargoCutoff;
            @XmlAttribute(name = "time-empty-pickup")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar timeEmptyPickup;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the inVoyNbr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInVoyNbr() {
                return inVoyNbr;
            }

            /**
             * Sets the value of the inVoyNbr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInVoyNbr(String value) {
                this.inVoyNbr = value;
            }

            /**
             * Gets the value of the outVoyNbr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOutVoyNbr() {
                return outVoyNbr;
            }

            /**
             * Sets the value of the outVoyNbr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOutVoyNbr(String value) {
                this.outVoyNbr = value;
            }

            /**
             * Gets the value of the timeCargoCutoff property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTimeCargoCutoff() {
                return timeCargoCutoff;
            }

            /**
             * Sets the value of the timeCargoCutoff property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTimeCargoCutoff(XMLGregorianCalendar value) {
                this.timeCargoCutoff = value;
            }

            /**
             * Gets the value of the timeEmptyPickup property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTimeEmptyPickup() {
                return timeEmptyPickup;
            }

            /**
             * Sets the value of the timeEmptyPickup property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTimeEmptyPickup(XMLGregorianCalendar value) {
                this.timeEmptyPickup = value;
            }

        }

    }

}
