--FRM_JOB_DEFINITION (all changed to tosdevteam id)
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'MAERSK UNITS IN KODIAK COMMUNITY';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'RECEIVE_APL_FLEET';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'NYK COMMUNITY REPORT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'NYK DUT EMPTY AT YARD REPORT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'MAERSK DUT INV REPORT EMAIL';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'CHIGNIK COMMUNITY REPORT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'NAKNEK COMMUNITY REPORT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'RECEIVE_NYK_BOOKING';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'SEND_NYK_322';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'UPDATE UE WITH UNIT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'MAERSK DUT RFR REPORT EMAIL';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'MAERSK KDK INV REPORT EMAIL';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'MATSONANCWRITETICKETINTOFTPPATH';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'SANDPOINT COMMUNITY REPORT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'DUTCH COMMUNITY REPORT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'SNX INBOUND KDK';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'SNX INBOUND DUT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'MATSONANCWRITETICKETINTOFTPPATH2';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'MAERSK KDK EMPTY AT YARD REPORT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'MAERSK DUT EMPTY AT YARD REPORT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'MAE DUT EMPTIES IN DUTCH AND NL';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'NYK DUT REEFER REPORT EMAIL';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'POST_SNXMAILBOX_ERROR_TO_JMS';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'ANK GATE CARRIER TRANSACTION REPORT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'AKUTAN COMMUNITY REPORT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'NYK DUT INV REPORT EMAIL';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'NYK DUT EMPTY AT YARD REPORT - DUT ';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'NYK DUT INV REPORT EMAIL - DUT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'NYK DUT REEFER REPORT EMAIL - DUT';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'SNX INBOUND ANK';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'SEND_MAE_322';
UPDATE TOSMGR.FRM_JOB_DEFINITION SET MESSAGE_RECEIVAL_ADDRESS ='1aktosdevteam@matson.com' WHERE ID = 'RECEIVE_MAE_BOOKING';
--GENERAL REFERENCES (rest all uses URL's)
update tosmgr.argo_general_reference set value1 = ? , value2 = ? where reftype='MATSON' and id1='RESTFULLTDP' and id2='URL';
update tosmgr.argo_general_reference set value1 = ?  where reftype='MATSON' and id1='GEMSPRETRIP' and id2='URL';
update tosmgr.argo_general_reference set value2 = '1AKTOSdevteam@matson.com'  where reftype='MATSON' and id1='EMAIL' and id2='SHOP';
-- HARDWARE (need to st as empty or ??? PP id's???)
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET HOST_ADDRESS = '10.157.32.93:9100' WHERE CLASS ='PRINTER' AND ID ='TROUBLET'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET HOST_ADDRESS = '10.157.32.77:9100' WHERE CLASS ='PRINTER' AND ID ='SHOP'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET HOST_ADDRESS = '10.157.32.93:9100' WHERE CLASS ='PRINTER' AND ID ='TROUBLE'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET HOST_ADDRESS = '10.157.32.219:9100' WHERE CLASS ='PRINTER' AND ID ='LANE1'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET HOST_ADDRESS = '10.157.33.15:9100' WHERE CLASS ='PRINTER' AND ID ='LANE2'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET HOST_ADDRESS = '10.157.33.1:9100' WHERE CLASS ='PRINTER' AND ID ='LANE3'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET HOST_ADDRESS = '10.157.32.215:9100' WHERE CLASS ='PRINTER' AND ID ='LANE4'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET HOST_ADDRESS = '10.3.6.38:9100' WHERE CLASS ='PRINTER' AND ID ='OAKPRINT'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET HOST_ADDRESS = '10.157.32.94:9100' WHERE CLASS ='PRINTER' AND ID ='GATEHOU'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET HOST_ADDRESS = '10.157.32.94:9100' WHERE CLASS ='PRINTER' AND ID ='LASER1'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET HOST_ADDRESS = '10.157.32.239:9100' WHERE CLASS ='PRINTER' AND ID ='GATEHNEW'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET CONSOLE_ID = '10.157.32.238' WHERE CLASS ='CONSOLE' AND ID ='REAR'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET CONSOLE_ID = '10.157.32.228' WHERE CLASS ='CONSOLE' AND ID ='RIGHT'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET CONSOLE_ID = '10.157.32.218' WHERE CLASS ='CONSOLE' AND ID ='MIDDLE'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET CONSOLE_ID = '10.157.32.205' WHERE CLASS ='CONSOLE' AND ID ='LEFT'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET CONSOLE_ID = '10.157.32.239' WHERE CLASS ='CONSOLE' AND ID ='AGING'  AND LIFE_CYCLE_STATE ='ACT';
UPDATE TOSMGR.ROAD_HARDWARE_DEVICES SET CONSOLE_ID = '10.157.32.232' WHERE CLASS ='CONSOLE' AND ID ='EQCTRL'  AND LIFE_CYCLE_STATE ='ACT';

UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='RECEIVE_APL_FLEET';
UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='RECEIVE_MAE_BOOKING';
UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='RECEIVE_NYK_BAPLIE';
UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='RECEIVE_NYK_BOOKING';
UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='SEND_GEMS_STOW_RECON';
UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='SEND_MAE_322';
UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='SEND_MAE_322_DISH';
UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='SEND_MAE_322_INGATE';
UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='SEND_MAE_322_LOAD';
UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='SEND_MAE_322_OUTGATE';
UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='SEND_MAE_BAPLIE_FTP';
UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='SEND_NYK_322';
UPDATE TOSMGR.EDI_MAILBOX set EDI_MAILBOX.COMM_ADDRESS='10.102.0.29' where EDI_MAILBOX.COMM_TYPE='FTP' and EDI_MAILBOX.NAME='SEND_NYK_BAPLIE';

UPDATE TOSMGR.REF_SNX_MAILBOX set REF_SNX_MAILBOX.COMM_ADDRESS='10.102.0.29' where  REF_SNX_MAILBOX.NAME='GATE-TICKET MAILBOX' and REF_SNX_MAILBOX.COMM_TYPE='FTP';
UPDATE TOSMGR.REF_SNX_MAILBOX set REF_SNX_MAILBOX.COMM_ADDRESS='10.102.0.29' where  REF_SNX_MAILBOX.NAME='SNX MAILBOX ANK' and REF_SNX_MAILBOX.COMM_TYPE='FTP';

	

commit;
